### ISSUE TITLE
false filtering when setting combineInstallments to false

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#109]
Hi,
https://github.com/eshaham/israeli-bank-scrapers/blob/5f6244c34e72acf5f8d13995d74d4f5bd16456ac/src/helpers/transactions.js#L38-L42

when `combineInstallments === false` the function `filterOldTransactions` filters the transactions using the `processedDate` property. 

This is function fails to exclude transactions that were processed in a relevant month but were created in a previous month. Is there a reason we cannot always filter by `Date`?

Thanks
Eran.

**The cli values that were used**
```
? What would you like to do? Run an individual scraper
? Which bank would you like to scrape? Leumi Card
? Combine installment transactions? No
? What date would you like to start scraping from? Nov 1, 2017
? Save folder? /Users/eransakal/Downloads/Transactions
```

**Resulted report**
![image](https://user-images.githubusercontent.com/4751797/38365696-fe07e480-38e5-11e8-8ce7-c09b067faa73.png)

**Comment by esakal** [comment]
When you choose not to combine installment transactions you want to keep them separately so following your example you will have 3 separated transactions as you described. But the meaning of `What date would you like to start scraping from?` changes when we are talking about separated (not combined) installments transactions . In such a scenario you expect seeing each installment as separated transactions and to scrape only those that confirm with the start date. This is how it appears in the bank sites as well when you choose to see a monthly transactions. 


See the below example, taken from my real finance data. Once I scrape with the following parameters, I expect only the black values to be scraped, but I get also the grayed ones. 

```
? What would you like to do? Run an individual scraper
? Which bank would you like to scrape? Leumi Card
? Combine installment transactions? No
? What date would you like to start scraping from? March 1, 2018
? Save folder? /Users/eransakal/Downloads/Transactions
```

![image](https://user-images.githubusercontent.com/4751797/38465113-afeae648-3b20-11e8-8543-875a5c06b8c0.png)

**Comment by eshaham** [comment]
@esakal ok, I think I got it now.
I think you are right, we could simply use the `date` property, since it is already adjusted in the `fixInstallments()` function.
I think the correct filter code should be:
```node
startMoment.isSameOrBefore(txn.date);
```
Once we only compare to `txn.date`, there rest of the checks are redundant.
Is this what you had in mind?

**Comment by esakal** [comment]
https://github.com/esakal/israeli-bank-scrapers/blob/d726f2f31b2d0dfbe1da3ad486df381bfa8331ea/src/helpers/transactions.js#L38-L45

Not exactly, because the `combineNeededAndInitialOrNormal` condition is mandatory if you choose to combine transactions. In such a scenario you want to filter out any transaction that is installment and is not the initial transaction. So I thing the fix should be to replace `processedDate` with `date` and to leave the other conditions as-is

```
export function filterOldTransactions(txns, startMoment, combineInstallments) {
  return txns.filter((txn) => {
    const combineNeededAndInitialOrNormal =
      combineInstallments && (isNormalTransaction(txn) || isInitialInstallmentTransaction(txn));
    return (!combineInstallments && startMoment.isSameOrBefore(txn.date)) ||
           (combineNeededAndInitialOrNormal && startMoment.isSameOrBefore(txn.date));
  });
```

**Comment by eshaham** [comment]
> Not exactly, because the combineNeededAndInitialOrNormal condition is mandatory if you choose to combine transactions. In such a scenario you want to filter out any transaction that is installment and is not the initial transaction. So I thing the fix should be to replace processedDate with date and to leave the other conditions as-is.

Shit, you're right. You're suggested code changes make sense.

> btw, I'm not sure that summary play nice with combine installments because basically combine installments alter the real balance of the card

Balance under summary should reflect the real balance of the account, meaning that if you've only paid the first installment out of several, balance would include the remaining payments, even if you specified to combine installments.

> Can you share the original purpose being the combine installments feature? in which use-case is it in use?

Some people, and under some use cases, one would prefer to refer to the initial transaction full amount as the source of truth for the transaction amount. If I spent 1000 ILS in August, that means that I spent 1000 ILS in August, even if I divided it into installments. This could be useful in many scenarios - for example if I want stats for how much I spent on electronics each month.

**Comment by esakal** [comment]
>  You're suggested code changes make sense.

Created #113

> Balance under summary should reflect the real balance of the account, meaning that if you've only paid the first installment out of several, balance would include the remaining payments, even if you specified to combine installments.

Sounds reasonable

> Some people, and under some use cases, one would prefer to refer to the initial transaction full amount as the source of truth for the transaction amount. If I spent 1000 ILS in August, that means that I spent 1000 ILS in August, even if I divided it into installments. This could be useful in many scenarios - for example if I want stats for how much I spent on electronics each month.

I didn't think about this scenario. sounds reasonable as well
