### ISSUE TITLE
Leumi Card Error: unknown transaction type

### ISSUE THREAD

**Issue by DedupOperator** [eshaham/israeli-bank-scrapers#118]
node.js terminates after multiple leumi-card module returns error code:
(node:4061) UnhandledPromiseRejectionWarning: \
    Error: unknown transaction type חודשי + ריבית

leumi-card.co.il shows regular transactions abroad as "חודשי + ריבית"
For trying to temporarily debug the issue, changing the variable (line 177) on the leumi-card.js generated module to:
var MONTHLY_CHARGE_TYPE_NAME = 'חודשי + ריבית';
confirmed working with no issue.

I suggest adding another transaction type, rebuilding the transaction types scheme, or including "חודשי + ריבית" as well as "רגילה" to the NORMAL_TYPE_NAME transaction name in the leumi-card module.

Btw, nice project idea!

**Comment by eshaham** [comment]
@DedupOperator thanks for reporting this, I will try to fix this soon

**Comment by DedupOperator** [comment]
Thank you very much.
I'll kindly help provide samples to clarify and also betatest

**Comment by DedupOperator** [comment]
Just to clarify, _all_ the 'Matach' transactions are displayed as "חודשי + ריבית" type.
As so, I think it should be addressed as an issue, not an improvement.


![for-israeli-bank-scrapers1of2](https://user-images.githubusercontent.com/38059469/41192493-3aa7bdc6-6c07-11e8-9b2e-a74e156059b7.png)
![for-israeli-bank-scrapers2of2](https://user-images.githubusercontent.com/38059469/41192492-3a7fe56c-6c07-11e8-8f7b-88a58973cf88.png)
