### ISSUE TITLE
setup credentials (for playground) doesn't override previous credentials.

### ISSUE THREAD

**Issue by ifeins** [eshaham/israeli-bank-scrapers#143]
A few days ago I've setup credentials for playground (using `npm run setup`) for Visa Cal to debug an issue.
Today I've setup credentials for Isracard and when I ran `npm run start` it still attempted to scrape Visa Cal instead of Isracard.

**Comment by ifeins** [comment]
Actually, that's not the issue, I see that it creates separate credentials files for each scraper.
The issue is that `npm run start` doesn't prompt the user to specify which scraper he/she wants to use.

**Comment by esakal** [comment]
@ifeins actually it works as designed. `npm run start` executes scraping immediately without prompting the user for information, this is done as described to allow [debugging from IDEs](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#debug-your-changes-using-the-ide) like webstorm. 

You should use the `npm run setup` to select which scraper to use when running. Once you run the setup and select `Setup options`, the first question will be which scraper to use as demonstrated below.

![image](https://user-images.githubusercontent.com/4751797/42530826-d9de8dfc-848a-11e8-9106-a5605fa0e425.png)

Please try this out and let me know if you have additional questions.

**Comment by ifeins** [comment]
@esakal Got it, thanks 👍 
Will close the issue.
