### ISSUE TITLE
tnx status could be change to boolean

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#148]
in tnx `status` can be completed or pending.
this can be changed to isCompelted true|false

**Comment by esakal** [comment]
Hi, it could be boolean, but I'm not sure if it is that important as we are using constant values quite frequently. Any concrete reason for changing the API? 

The reason I'm asking is that changing public api affect not only all this library scrapers but also all other applications that consume this one. So I'm not favoring changing things unless it improve a functionality or fix a problem.

**Comment by lielran** [comment]
you find your copy this string into your code for no good reason. I guess that we need to decide if to change it someday and break compatibility(maybe before v1.0)

**Comment by esakal** [comment]
well copy a string that is considered an enum is the same for me as knowing that the property is boolean, number, nullable etc... I leave this call to @eshaham

**Comment by eshaham** [comment]
@lielran While I'm ok with breaking changes before v1.0, I actually prefer the status approach.
Closing this for now.
