### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by lielran** [eshaham/israeli-bank-scrapers#152]
what do you think about moving to Typescript?

**Comment by esakal** [comment]
I'm a fan of typescript and I use it daily at work, but as the library is not that big it is not that important if it will use it or not.  Whether we should use it for this library or not it is subjective and depends on the preference of @eshaham and the rest of the contributors.

**Comment by lielran** [comment]
since it's a library + we have 0 tests to prove things are working, I think that the benefit here is fewer bugs/issues.

**Comment by eshaham** [comment]
@lielran not a fan of Typescript either, I love the simplicity of pure ES6.
I would like to put more effort into writing tests.
Closing this for now.

**Comment by eshaham** [comment]
@esakal still waiting for a typed language I had a good connection with - Typescript is definitely not it.
I feel it takes the fun out of Javascript, and it's one of the main reasons I'm staying away from later versions of Angular (used to love Angular 1).

**Comment by amitdahan** [comment]
Hey guys! Almost 2 years later, any chance the opinions above changed? 🤞🤞🤞

Really appreciate the work being done here regardless!

**Comment by amitdahan** [comment]
Does this mean you guys'll accept my PR?

**Comment by esakal** [comment]
Not yet :) I re-open the ticket for discussion. Last time we discussed about it @eshaham didn't favor Typescript. Let's wait for his insights about it.

**Comment by esakal** [comment]
@lielran just a short update (so the bot will not close this issue :) )
We are working on Typescript support here #404

**Comment by lielran** [comment]
Thanks Eran!

**Comment by esakal** [comment]
.
