### ISSUE TITLE
scrape charged currency for credit cards

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#155]
We are missing charged currency when scraping credit cards. This information is needed as the user can choose whether to link his credit card to local bank account or foreign bank account. Without charged currency the value of charged amount means nothing. 

I implemented that support for `leumi card scraper` in branch [charged-currency](https://github.com/eshaham/israeli-bank-scrapers/tree/charged-currency). the following shows the scraping of my card from with support to all 3 use cases (`ILS->ILS`, `USD->ILS`, `USD->USD`):
![image](https://user-images.githubusercontent.com/4751797/44949712-d258ae80-ae3f-11e8-88a3-e29d0ca00eb0.png)

@eshaham,  If you find it relevant we can use that branch to add support for other cards. wdyt?

**Comment by esakal** [comment]
Yes it does :) I missed that one. So great I will continue and add support for `leumi` foreign account and hopefully @asfktz will add support for Poalim and Isracard

**Comment by asfktz** [comment]
Nice! I'm happy to see that.
I have so much love for this project (:

Yeah, I'll be able to add support for Poalim and Isracard.
I'm not available for open source so much lately, so it might take some time.

**Comment by esakal** [comment]
closing this issue as it is a duplicate of #80
