### ISSUE TITLE
Leumi card login result undefined

### ISSUE THREAD

**Issue by guygberg** [eshaham/israeli-bank-scrapers#169]
Hello

When I try to use a simple code to read the transactions from Leumi card.
I get an error "'unexpected login result "undefined"'"

Code 
it is surrond by an iife to be able to run the await
and the credentials are initialize correctly (same as your example) 
![image](https://user-images.githubusercontent.com/40508367/50573278-a5aaa880-0dd9-11e9-91dd-ef9a4d00f23c.png)

The error:
![image](https://user-images.githubusercontent.com/40508367/50573285-cbd04880-0dd9-11e9-843a-b4c606f5639f.png)

Can you please find the reason for this?

**Comment by eshaham** [comment]
@guygberg I just tried to reproduce it with your code with my LeumiCard account, but it worked perfectly.
maybe you can try to print `scraperResult.errorMessage`?
I will need more info to help with this one.

**Comment by guygberg** [comment]
@eshaham  Thank for your resonance.
Now I get an [object, object] using this.
Please see below
![image](https://user-images.githubusercontent.com/40508367/51388165-42d34400-1b31-11e9-85de-3fb503cd765f.png)

**Comment by esakal** [comment]
hmmm.... actually writing `console.log` should work regardless to the `browser` option. Can you please verify that:
1. you changed the file under `node_modules/israeli-bank-scrapers/lib` and not under `.../src`
2. that the change was actually saved (some IDE's prevent changing of files under `node_modules`
3. if that doesn't work change `console.log` to `console.error` maybe it is filtered somehow
4. if still doesn't work, add `showBrowser: true` to the options object` which will show the browser and you will be able to copy the mentioned url.
5. if still doesn't work change it to `throw new Error('login resulted with url: ' + current)`
6. if still doesn't work, move it one line above (under the `var current = ...`)

hopefully one of the above will write the url to the console so we will be able to compare the url

**Comment by guygberg** [comment]
Thanks @esakal 

I have tried all the options with no success.
I have debug to see that my progrem does no reach that line.
I get an error thrown on the function waitUntil (I get a timeout)
The URL that I see along the debug is always:
"https://online.leumi-card.co.il/Anonymous/Login/CardHoldersLogin.aspx"

Do you know why do I get a timeout?

Regards
Guy

**Comment by esakal** [comment]
Hi,
Let's try to quickly nail down this issue. From your attached image I understand that you are working with the playground? this is good as it means that you see the browser while scraping. 

function `waitUntil` is used by`waitForRedirect`. Leumi scraper is using it as part of the login process [here](https://github.com/eshaham/israeli-bank-scrapers/blob/aef7c676b5279cd16f133a521f0abf9df4ad056d/src/helpers/navigation.js#L27)
```
function redirectOrDialog(page) {
  return Promise.race([
    waitForRedirect(page),
    waitUntilElementFound(page, '#popupWrongDetails', true),
  ]);
}
```
You stated that the page that you get timeout on `https://online.leumi-card.co.il/Anonymous/Login/CardHoldersLogin.aspx` which can mean two things:
1. the request was not actually executed after pressing the submit button (element with id `PlaceHolderMain_CardHoldersLogin1_btnLogin`).  It might happen if the button has a different id (not that likely) or more likely if the user/password you provided didn't pass the **client validation as you can see in the image below**
![image](https://user-images.githubusercontent.com/4751797/52522960-9a7a5080-2c94-11e9-8f0e-1b3b6c721379.png)

2. the request was sent and you were redirected to the same page. It happen if you provided wrong user/password and then you reach the same page with the element seen below (element with id `popupWrongDetails`). You will get timeout if your page doesn't include that element.
![image](https://user-images.githubusercontent.com/4751797/52522875-a9143800-2c93-11e9-8a7d-598b59fa6376.png)

Can you see if one of the scenarios happen to you? 

To be able to further diagnose your problem, It would be very helpful if you will attach a snapshot of the page after the login process. 

Also you can set breakpoints in the `login()` function of ``  [here](https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/base-scraper-with-browser.js#L107) and see if my assumption is right and you are reach line 130
```
async login(credentials) {
    if (!credentials) {
      return createGeneralError();
    }

    const loginOptions = this.getLoginOptions(credentials);

    await this.navigateTo(loginOptions.loginUrl);
    if (loginOptions.checkReadiness) {
      await loginOptions.checkReadiness();
    } else {
      await waitUntilElementFound(this.page, loginOptions.submitButtonSelector);
    }

    await this.fillInputs(loginOptions.fields);
      await clickButton(this.page, loginOptions.submitButtonSelector);
    this.emitProgress(SCRAPE_PROGRESS_TYPES.LOGGING_IN);

    if (loginOptions.postAction) {
      await loginOptions.postAction();  <------- I'm assuming you get timeout on this line
    } else {
      await waitForNavigation(this.page);
    }

    const current = await getCurrentUrl(this.page, true);
    const loginResult = getKeyByValue(loginOptions.possibleResults, current);
    return handleLoginResult(this, loginResult);
  }
```

Let me know how it goes.
Eran.

**Comment by guygberg** [comment]
I have made some progress.
I do get success on login in:
![image](https://user-images.githubusercontent.com/40508367/52535700-5d789180-2d5a-11e9-804c-6124f3868e59.png)

But I after the function finishes I get the below:
Do you know why?
![image](https://user-images.githubusercontent.com/40508367/52535725-84cf5e80-2d5a-11e9-9077-354afe69e8ec.png)

Thanks
Guy

**Comment by guygberg** [comment]
@esakal
I was able to overcome the issue.
I want to thank you for all your help.
Hope it would be easier to connect to me Poalim card :)

**Comment by esakal** [comment]
@guygberg great news! Let us know if you will need further assistance with the Poalim 👍
