### ISSUE TITLE
Getting extra input from the user

### ISSUE THREAD

**Issue by Urigo** [eshaham/israeli-bank-scrapers#171]
I'm working on the business version of Hapoalim.

I got it all running locally including getting the foreign and credit card transactions

The thing is, that in a business account once you have a successful login they send you SMS with a code.
I've added a command prompt locally to get it working easily for me, but I wonder what would you think would be the best way to add something like that in the current way the code and the login flow is set up?

thanks

**Comment by esakal** [comment]
Hi @Urigo,
I saw your question earlier today. While playing with our codebase I ended up implementing this feature as it felt natural extension to the login process.

@eshaham can you please review my solution in pr #172, I think we achieve an important support with efficient code extension. It is not ready yet until @Urigo will create a PR to branch `sms-verification` with the relevant Hapoalim selectors/url but beside that it seems ready.

@Urigo as said above, please pull `sms-verification`. I added `TODO Urigo: ...` comments in `hapoalim.js` file as placeholders. Once it works just create a PR with your additions. If you are using the Playground support to test your scraper, I already extended the playground to support it, otherwise assign `smsVerificationHandler` with a relevant handler

Any insights?

**Comment by Urigo** [comment]
hi again and sorry for the very late response.

@esakal thank you so much for the PR, it was very clear.

The reason I haven't responded was that I was focusing on finishing the project that uses the new scraper so I would make sure I run it every day.
Now it is the case and I am very happy with it :)

Now I want to contribute it back to the codebase.

The main question I have is that (and probably it should go into a separate issue) - how import and helpful is the current class structure for you?

My very personal opinion while working on the scraper, even though it was probably the most similar scraper out there to another scraper (Poalim), have the class setup just made it harder.
At some point I just converted all functions to be stateless and just created by own flow, some of it similar to the current Poalim and some not.

The functional helper directory was very helpful and I kind of expended it with code from the current Poalim scraper and just created my own flow instead of confirming to the flow dictated but the base class.

I understand the idea of exposing the same API from all scrapers in order to have a single runner with similar status and steps updates, but what is that runner?

I think each developer would probably create their own runner in case they will create a general application and that runner will expect statuses, steps and errors that are specific to that parent application.

It is probably not my place to ask for it but have you thought about changing the structure into a lot of helper functions, some specific to a bank, some general and some just wrapping a bunch of other functions for a mini-flow?

**Comment by Urigo** [comment]
by the way, in my code I take all transactions from dollar and euro accounts, I take all the credit card transactions 6 months back and I take the balances of the credit card (shekel, dollar and euro) and  checking balance (shekel, dollars and euro)

**Comment by Urigo** [comment]
maybe it's just a matter of changing some function to be static, like `convertTransactions`, `getRestContext`, `fetchPoalimXSRFWithinPage`, `fetchAccountData`.
Then I can use them if I want but not conform to the flow dictated by the base class.
I've also added a version of `fetchPoalimXSRFWithinPage` but that uses GET in order to send some more requests I needed

**Comment by eshaham** [comment]
> The main question I have is that (and probably it should go into a separate issue) - how import and helpful is the current class structure for you?

While I usually try to stick to functional coding whenever I can, I think that in this case the current class structure really makes sense for me. It adds a clear structure, makes it very clear to implementers what they need to override, and creates a common language between scrapers.

> maybe it's just a matter of changing some function to be static, like convertTransactions, getRestContext, fetchPoalimXSRFWithinPage, fetchAccountData.

That makes more sense for me, but even then, if we want to allow scrapers to expose other functions such as the ones you mentioned above, we would need to create a clear definition of the functions and what each scraper should / can expose.

**Comment by Urigo** [comment]
> It adds a clear structure, makes it very clear to implementers what they need to override, and creates a common language between scrapers.

True. But why does different scrapers need a common language?

and why would they need to expose the same thing?

**Comment by esakal** [comment]
> The reason I haven't responded was that I was focusing on finishing the project that uses the new scraper so I would make sure I run it every day.
Now it is the case and I am very happy with it :)

Being able to use "open financing" is awesome and this is why I love this project.

> It is probably not my place to ask for it but... 

God bless open-source projects, everyone can ask everything and contribute as they can. 

> ...have you thought about changing the structure into a lot of helper functions, some specific to a bank, some general and some just wrapping a bunch of other functions for a mini-flow?

Your question is interesting when talking about the implementation details used here of scrapers and ways to simplify creation of new ones. People who consume this library from NPM don't actually care about it so I think your question is relevant only to few selected people that want to create their own scrapers with potentially different public response type and use this library as a set of building blocks (i.e block that login to leumi, block that filter list of transactions of leumi etc).

As I didn't find your project I don't really know how you are leveraging this library to your own needs and can only say that generally like @eshaham (and I assume you as well) I prefer FF where possible.  Whether it worth refactoring this library or not is a good question, I think it should be only if we think people wants to use this library to scrape other things beside transactions.

> I understand the idea of exposing the same API from all scrapers in order to have a single runner with similar status and steps updates, but what is that runner?

I do think having a single api is useful (with the exception of the credentials part which vary between sites). But it doesn't contradict the building block concept. This library can provide predefined scrapers as it does today which internally will use the same building blocks that will be exposed by this library. 

@Urigo is your project private or public? if public please send a link as I didn't find it in your repositories list.

**Comment by esakal** [comment]
@Urigo lets continue the discussing about stateless logic in #186 and keep this PR for discussion about its original context. Note that if we will choose to continue with #186 it should be easy to add such a support without affecting the existing flow

**Comment by baruchiro** [comment]
> @Urigo lets continue the discussing about stateless logic in #186 and keep this PR for discussion about its original context.

So, I see the #186 is merged. Any updates?

**Comment by esakal** [comment]
#186 was not merged, it was closed. I created a branch that is using adapters. I need to complete it and add documentation. @Urigo should use this PR to add bank hapoalim business login adaper so we will be able to "feel" the scalability and then Elad should review everything and provide his inputs.

I will create a draft PR later this week with a list of open tasks.
