### ISSUE TITLE
Leumi Card scrapper stopped working

### ISSUE THREAD

**Issue by bsorek** [eshaham/israeli-bank-scrapers#179]
I get the following error. Seems like it logs in ok but the return value after login is not recgnized:
Leumi Card: START_SCRAPING
Leumi Card: INITIALIZING
Leumi Card: LOGGING_IN
Leumi Card: TERMINATING
Leumi Card: END_SCRAPING
success: false
error type: generic
error: unexpected login result "undefined"
Error: unexpected login result "undefined"
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:62:11
    at Generator.next (<anonymous>)
    at step (/Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:191)
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:361
(node:7970) UnhandledPromiseRejectionWarning: Error: unexpected login result "undefined"
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:62:11
    at Generator.next (<anonymous>)
    at step (/Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:191)
    at /Users/bsorek/Dev/git/personal/bankapp/israeli-ynab-updater/src/scrape/scrape-base.js:47:361
(node:7970) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7970) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by esakal** [comment]
hi @bsorek , usually this error indicate on either:
1. user/pass expired or going to be expired (which means that leumi card shows a blocker popup).
2. user/pass invalid

Please try the following:
1. retype the user/password into israeli-ynab-updater
2. connect to leumi-card with that user/pass and make sure it works.

if it still happens let me know if you it happens immediately or after appx 30 seconds after getting the `Leumi Card: LOGGING_IN` status

**Comment by bsorek** [comment]
Hi,
I tried logging in directly and worked fine.I get the message immediately after seeing the LOGGING_IN status. I ran the scraper in debug, and I see that it successfully logged in but then there is an error. We see the dialog box that says it's redirecting me to my account, and as soon as the dialog disappears the exception occurs.

**Comment by vmalloc** [comment]
I believe this is because of the recent redesign the Leumi-card website has undergone. It has been rebranded (as "Max"), and from the looks of it it looks like the login flow has changed (I had a scraper of my own that stopped working today as well)

**Comment by esakal** [comment]
@vmalloc You are correct, it does happen now that they rebranded. but unfortunately they played with the flow as well. I will try to resolve it tomorrow and provide a PR.

**Comment by esakal** [comment]
@bsorek I created a pr fixing the broken scraper #180. You can pull it and test it as well until @eshaham will review it.
