### ISSUE TITLE
Monthly postponed payment error

### ISSUE THREAD

**Issue by bsorek** [eshaham/israeli-bank-scrapers#182]
Getting an error `error: Unknown transaction type דחוי לחיוב החודשי` 
These are monthly transactions done for recurring monthly subscription such as AMAZON PRIME in US dollars.
<img width="689" alt="Screen Shot 2019-03-10 at 20 13 06" src="https://user-images.githubusercontent.com/5676596/54093748-60729c00-4371-11e9-9c01-22ce6a3395e7.png">

**Comment by esakal** [comment]
@bsorek can you pull my PR and reply if it solves your issue?

**Comment by bsorek** [comment]
tested, and it works. Thanks

**Comment by bsorek** [comment]
@esakal was a new version pushed to NPM? I am trying to use the ynab-updater, but it still fails using version 0.6.5

**Comment by esakal** [comment]
@eshaham can you please publish a new version?

**Comment by esakal** [comment]
@bsorek in the meanwhile untill Elad will deploy a new version,  you can use a local version of the library. You might already know it but just in case:
1. in the ynab root folder link it to npm `npm link` (make sure you pulled master)
2. in your library root folder link to the local version by `npm link israeli-ynab-scrapers`

It should work until next time you run `npm install` in your library (and then you will need to repeat those steps).

Hopefully it helps

**Comment by eshaham** [comment]
@bsorek @esakal sorry for the delay, needed to set up a temporary workstation.
published everything now.
