### ISSUE TITLE
Leumi card scraper has stopped working

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#217]
When running the scraper in the last few days I get the following error:

scraping failed for the following reason: GENERIC
Failed scraping  leumiCard
Error while trying to navigate to url https://online.max.co.il/Registred/Transactions/ChargesDeals.aspx?ActionType=2&MonthCharge=201907&Index=-2

**Comment by liranso** [comment]
It seems like they change the transaction page completely.
I'm working on a fix on my end

**Comment by eshaham** [comment]
@liranso I noticed they now transfer the list of transactions via a REST call, which will be much either for scraping purposes (see discount scraper for an example).
It is important to take this route, as it is much more reliable.

**Comment by liranso** [comment]
Exactly,
I'm going to use the browser for login, and then make rest calls to get JSON response for each month
Is that what you though about?

**Comment by eshaham** [comment]
indeed 👌

**Comment by liranso** [comment]
what about conventions?
i saw that the adapter is using generators 
what if i use async await for some of the new function?

**Comment by liranso** [comment]
I want to create a branch for a PR
Can you give me permissions?
Also, i have some question about the "fix installments" code

**Comment by esakal** [comment]
Hi @liranso thanks for your contribution. To submit a PR  its easy, jusr fork this library into your owb user, and create a PR from there into this repository.

What is your question about the fix installments?

**Comment by liranso** [comment]
Ok, no question about the installments, I understand the purpose.
Created a PR

**Comment by eshaham** [comment]
fixed by #219
