### ISSUE TITLE
Leumi card scraper does not get the amount of the transactions

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#227]
Since the fix for issue #217 the leumi card scraper does return the transactions successfully but many of them with amount -0.

**Comment by esakal** [comment]
Hi @brafdlog, can you please enter the site and check if those transactions are marked as pending transactions? meaning "עסקאות שאושרו וטרם נקלטו"

**Comment by esakal** [comment]
If I'm correct, those are transactions that are marked as pending and tomorrow you will see them as regular transactions with the real amount. Please make sure to either check it today or not overriding the output tomorrow when you try again so you will be able to compare todays scraping and the new one tomorrow

**Comment by brafdlog** [comment]
That seems to be the case.

So is this the expected behaviour? If so I will just filter out those transactions until they are no longer pending and get the real result.

**Comment by esakal** [comment]
This is the expected behavior. As those transactions are not approved yet so the API returns 0 for actual payment. 

Just use the status column, in my applications I always ignore transactions with pending status.

Im glad it is resolved :)
