### ISSUE TITLE
Leumi scraper throws an error when there are no transactions during the given date range

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#231]
To find transactions the leumi scraper looks for the following selector: `table#WorkSpaceBox table#ctlActivityTable`. 

When there are no transaction in a specific date range, the table that this selector points to does not exist and instead the following message is shown:

<img width="666" alt="Screenshot 2019-07-28 17 07 28" src="https://user-images.githubusercontent.com/7272927/62007986-f3637580-b15c-11e9-8ac8-35f3ddf85980.png">

Since the selector does not exist, the scraper times out and throws an error.

**Comment by brafdlog** [comment]
Created a pr #232

**Comment by brafdlog** [comment]
@esakal Can you take a look at the pr?

**Comment by esakal** [comment]
fixed and merged  #232
