### ISSUE TITLE
Leumi card throws when there are no future transactions

### ISSUE THREAD

**Issue by asfktz** [eshaham/israeli-bank-scrapers#237]
Leumi card throws when there are no future transactions, at least I guess this is the case.
What I can tell for sure is that it falls in `fetchTransactionsForMonth` when `data.result` is `null`.
In my case, it happens when `monthMoment` is next month.

https://github.com/eshaham/israeli-bank-scrapers/blob/59b5056e2e66ff501c3861e0b19dc2c2b76949af/src/scrapers/leumi-card.js#L114-L124

PR https://github.com/eshaham/israeli-bank-scrapers/pull/236 fixes it by adding a null check.

**Comment by esakal** [comment]
fixed as part of #234
