### ISSUE TITLE
Make redirect ignore list more generic

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#241]
https://github.com/eshaham/israeli-bank-scrapers/blob/59b5056e2e66ff501c3861e0b19dc2c2b76949af/src/helpers/navigation.js#L25

In a new scraper, the login redirect contains a URL ends with `Default.aspx?language=he-IL`. I need the redirect will ignore the URL, no matter what is the query string.

The more complicated case is with URL like `Bank.com/he/index.html`, should ignore all `Bank.com/*/index.html`.

**Comment by esakal** [comment]
Hi @baruchiro, 
The login options exposes `postAction` interceptor for custom login handling. see [leumi](https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/leumi.js#L242) or any other scrapers that passes `postAction`

it should solve your case.

**Comment by esakal** [comment]
@baruchiro please let me know if I can close this issue
