### ISSUE TITLE
waitForSelector with iframe

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#248]
The command `page.waitForSelector` will wait until the timeout, if the `selector` is in `iframe`.

**Comment by baruchiro** [comment]
Additionally, clicking on an element found in the `iframe` will not perform as expected (no exception will be thrown, but the element will not be clicked).

**Comment by esakal** [comment]
is this a puppeteer issue or this library one? if this is puppeteer issue then I think you should check for relevant  issues in puppeteer repository.

**Comment by baruchiro** [comment]
This is kind of puppeteer issue, but we should handle it in our project.

If you Google about puppeteer with iframe, you will find some closed
issues. But in our project things still act different. So I think that's a
limitation, that we have to deal with it at our level.

**Comment by esakal** [comment]
Our focus in this library is on scraping transactions from Israeli institutes, we are using puppeteer as a framework to help us with this purpose. We should handle this use case only if we have a bug in one of the scrapers and you didn't find a workaround to this puppeteer issue. 

Where do you have this issue? in the Mizrahi scraper you are adding? if so please create a reproducible project and I will try to assist.

If this issue doesn't block you in any scraper (existing or new one) then I'm afraid it is not relevant to this repository.

**Comment by baruchiro** [comment]
Yes, it happens in the Mizrahi Scraper. I try some kinds of workarounds, but each one leads to a different problem. Therefore, it delays me too much and I try through another page.

I will see where there are more problems and by that we will decide what is the right way.

**Comment by esakal** [comment]
ok, let me know if you managed, if not create a reproducible example and I will try to assist

**Comment by esakal** [comment]
see comment [here](https://github.com/eshaham/israeli-bank-scrapers/issues/253#issuecomment-523620427) - might be relevant to this issue as well.

**Comment by eshaham** [comment]
@baruchiro @esakal can we close this issue?

**Comment by esakal** [comment]
I think we can since we already merge Mizrachi and this PR was created to support that scraper.

@baruchiro please confirm

**Comment by baruchiro** [comment]
OK, I don't remember, but probably I found a workaround or something.
