### ISSUE TITLE
Remove Line Breaking validation from lint

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#252]
Hi, in the `pre-commit` we run the `lint`, who is required to the `linebreaks to be 'LF'`.

But in Windows we work with `CRLF`, so we get the error: `Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`.

Anyway Git commits all files as `LF`.

**Comment by eshaham** [comment]
@baruchiro as long as you're sure the commit will be sent in LF, that makes sense.
PR welcomed 😄

**Comment by baruchiro** [comment]
I'm pretty sure it's like that, but I can't find anything accurate.

I'm looking for `checkout system style, commit LF`

**Comment by baruchiro** [comment]
According to [this](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems) in `lint` docs, I will change the `.gitattribute` file.

**Comment by eshaham** [comment]
@esakal was this fixed by #291?

**Comment by baruchiro** [comment]
Yes, #290 was supposed to close this.
