### ISSUE TITLE
Problems with Headers object

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#265]
https://github.com/eshaham/israeli-bank-scrapers/blob/443d44d757ca64a13aa675604c5d8be06b1c2152/src/helpers/fetch.js#L57-L77

I have a problem with line 64, it throws a `ReferenceError: Headers is not defined` error.

If I trying to use `nodeFetch.Headers` it works, but then in my MizrahiScraper, the method (`fetchPostWithinPage`) throws `Evaluation failed: ReferenceError: _nodeFetch is not defined`.

**Comment by eshaham** [comment]
@baruchiro code running under page.evaluate are evaluated in the context of the browser. So I don't think it has to do with node.
But this is really weird. Perhaps you can try to remove the Headers class and just use an object?
```
headers: { 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', ...extraHeaders }
```

**Comment by baruchiro** [comment]
If I using your solution I getting the error `ReferenceError: _objectSpread is not defined`.
So my solution will be to use `Object.assign`.
