### ISSUE TITLE
[Question] There is a plan for GUI?

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#269]
Hi, there is a plan for developing a GUI app (with Electron or something else)?

Or will I start developing myself?

**Comment by eshaham** [comment]
@baruchiro we don't have plans to create a GUI, especially not under this project. Feel free to develop one yourself, we'll be more than happy to link to it from README once it's ready.

**Comment by baruchiro** [comment]
@eshaham @esakal I started a [GUI project](https://github.com/baruchiro/israeli-bank-scrapers-desktop), and I planing to invite beta testers in the coming days.

I see my project as part of your project, so I want you to review **anything**, from the project name to design decisions.

More details are in the README.

**Comment by esakal** [comment]
Hi @baruchiro. I'm glad you enjoy israeli-bank-scrapers project and find it useful.
Israeli-bank-scrapers is an infrastructure that allow other people to develop their own applications. It was not intended to be a standalone solution. 

There are many decisions in the design that  confirm the state above. For example, when developing a local application using electron you should design for security as you store the user credentials locally. This is only one example to a decision point that doesn't confirm with the design of this repository which doesn't persist any user credentials.

Once you reach RC we can obviously add your project into [known-project](https://github.com/eshaham/israeli-bank-scrapers#known-projects) section but again it will remain a separated repository where you will be the author .

IMO this is not something that is in the roadmap of this library but let's wait to hear from @eshaham who is the owner of this library. 

@eshaham please share your thoughts.

BTW, your repo is using `yarn` as package manager but the `readme.md` file state that you work with `npm`. Consider fixing the installation instructions

**Comment by baruchiro** [comment]
Sorry, I didn't use the right words.

I totally agree on the idea of separating the repositories. What I meant to say is that because my project is (currently) intended to be a UI for `israeli-bank-scrapers`, I think @eshaham and @esakal will understand the needs he is trying to meet, and the requirements.

I generally invite you to do a review of my project because I think you understand it, and I appreciate your opinion as someone who maintains the library at its core.

**Comment by eshaham** [comment]
@esakal totally agree, this belongs in the known projects section. I think that's what @baruchiro had in mind anyway.
@baruchiro I'd be more than happy to go over your project and even use it, but might take some time until I get to it 😅
