### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by orzarchi** [eshaham/israeli-bank-scrapers#276]
Is there any reason why the new version has not been published to NPM? it's been 17 days.
I've had to create a fork just to publish it.

**Comment by eshaham** [comment]
I was sure I completed the release, sorry.
Done now.

**Comment by orzarchi** [comment]
Thanks!

**Comment by esakal** [comment]
@orzarchi  consider using the [prerelease version](https://github.com/eshaham/israeli-bank-scrapers#getting-deployed-version-of-latest-changes-in-master) next time, this is a new feature added following your issue to provide immediate solution for people once a fix was merged.
