### ISSUE TITLE
WaitUntil networkidle0 when you evaluate

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#277]
https://github.com/eshaham/israeli-bank-scrapers/blob/c0c1bccea7dedeeef0caeb258b4df75e5cbd629a/src/scrapers/base-scraper-with-browser.js#L147-L150

Without `options: { waitUntil: 'networkidle0' }`, the `waitForNavigation` will return before the page is loaded, and then, the next method- `getCurrentUrl` tring to `page.evaluate(() => window.location.href)` and throws `Execution context was destroyed, most likely because of a navigation`.

I get this exception when I trying to play with the `postAction` of **Mizrahi** scraper and adding `options: { waitUntil: 'networkidle0' }` to the `waitForNavigation` solve the problem.

**Comment by esakal** [comment]
I'm not sure why it happens to you and not to other scrapers but I see that you handled it in #256 
```
      postAction: async () => waitForNavigation(this.page, { waitUntil: 'networkidle0' }),
```
so i'm not sure if we actually need to modify the base class unless we will have issues in other scrapers
