### ISSUE TITLE
Bank Leumi failed with UNKNOWN_ERROR

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#296]
After login, the Bank Leumi scraper failed with `{success: false, errorType: "UNKNOWN_ERROR"}`

**Comment by esakal** [comment]
@baruchiro Until @eshaham will release an official version, feel free to use the prerelease version automatically published to npm. just install `npm run israeli-bank-scrapers@ next`

**Comment by baruchiro** [comment]
Also relevant to `-core`?

**Comment by esakal** [comment]
yes, it is part of the automatic process added lately. `npm run israeli-bank-scrapers-core@next`
