### ISSUE TITLE
Cannot read property 'transactions' of null

### ISSUE THREAD

**Issue by guygberg** [eshaham/israeli-bank-scrapers#299]
Hi

I have been using this leumi scraper.
I suddenly get the below error
Can you please help me understand what heppen?

"scraping failed for the following reason: GENERIC
scrapTreeWalkerd for the following reason: Cannot read property 'transactions' of null"

Regards
Guy

**Comment by eshaham** [comment]
@esakal do you have a Leumi account? Is the scraper working?
@guygberg maybe you can try debugging your code by running `node --inspect --inspect-brk <your_file>`?

**Comment by esakal** [comment]
Ah, I have missed this issue. It worked for me last time I checked. 
@eshaham it works for me, I just scraped two different accounts of Leumi.

@guygberg you can test your code as Elad suggested or run the sources directly as described [here](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#testing-the-scrapers)

If it still fails, please add some logs from the cli

**Comment by esakal** [comment]
@guygberg can you please update about this issue? was this resolved or still relevant?

**Comment by guygberg** [comment]
Nope all good.
Thank you very much

**Comment by esakal** [comment]
Great!
