### ISSUE TITLE
leumi scraper fails

### ISSUE THREAD

**Issue by liranso** [eshaham/israeli-bank-scrapers#300]
Login process succeeded but leading to a different page than the current code expected.
The "getPossibleLoginResults" implementation on the leumi adapter, should expect this **"/eBanking\/SO\/SPA.aspx/"** on login success instead of **/ebanking\/SO\/SPA.aspx/**.
(they change the B to be upper case).

**Comment by esakal** [comment]
Hi @liranso Actually it was already fixed as part of #296. see my last comment in that issue. Hope it helps.

> Until @eshaham will release an official version, feel free to use the prerelease version automatically published to npm. just install npm run israeli-bank-scrapers@next
