### ISSUE TITLE
Leumi Card scraper returns no transactions

### ISSUE THREAD

**Issue by ifeins** [eshaham/israeli-bank-scrapers#306]
I'm running the leumi card scraper and getting the following output:

```
➜  israeli-ynab-updater git:(master) npm start

> israeli-ynab-updater@0.0.1 start /Users/ifeins/Development/israeli-ynab-updater
> babel-node src

? What would you like to do? Run an individual scraper
? Which bank would you like to scrape? Leumi Card
? Combine installment transactions? No
? What date would you like to start scraping from? Nov 1, 2019
? Save folder? /Users/ifeins/Downloads/Transactions
? Include future transactions? No
? Include pending transactions? No
scraping Leumi Card
Leumi Card: START_SCRAPING
Leumi Card: INITIALIZING
Leumi Card: LOGGING_IN
Leumi Card: LOGIN_SUCCESS
Leumi Card: TERMINATING
Leumi Card: END_SCRAPING
success: true
Leumi Card: scraped 2 transactions from account XXXX
no transactions for account # XXXX
```

In the leumi card page I see that there are 2 transactions and it seems that the scraper is able to find them ("scraped 2 transactions from account...") however then it prints "no transactions".

Any idea why this happens?

**Comment by esakal** [comment]
Hi @ifeins from your attached code it seems that you are using a very old version of this library. We switched to unit-tests approach in July 12 and it seems that your code it using the old wizard cli.

Which version are your running?

**Comment by ifeins** [comment]
@esakal when you refer to "library", do you mean `israeli-ynab-updater` or `israeli-bank-scrapers`?
because the screenshot is from `israeli-ynab-updater` which has a dependency on `israeli-bank-scrapers`.
In any case I'm using the latest version of `israeli-ynab-updater` which uses version `0.6.9` of `israeli-bank-scrapers`.

I did however build the latest version of `israeli-bank-scrapers` and used `npm link` and now the leumi card scraper work so I get this issue can be closed.

**Comment by esakal** [comment]
@ifeins nice! I was confused because I built this CLI for both repositories and later removed it from this one. Anyway you should consider openning an issue in `israeli-ynab-updater` so Elad will be able to track that one and update its dependencies.

**Comment by ifeins** [comment]
@esakal @eshaham btw I believe that version 0.7.0 still does't have the latest changes, both for leumi-card and for bank-leumi. Can you draft a new release and publish to npm?

**Comment by esakal** [comment]
@ifeins publishing new versions is done by Elad. It is done manually at the moment due to lack of good unit-tests (since we scrape sites) so it might takes a while between deployment. 

To overcome this issue we added an automatic deployment that is triggered everytime we push things to master. it is tagged as `next` in npm [link](https://www.npmjs.com/package/israeli-bank-scrapers/v/0.7.1-dev.05bf4b6f0). 

I'm using the next version in my code. just run `npm i israeli-bank-scrapers@next` to get the latest one till Elad publish the `latest` version

**Comment by ifeins** [comment]
@esakal got it, thanks for the info.

@eshaham is there any specific cadence to releasing a new official version of `israeli-bank-scrapers`?

Alternatively is it possible to change `israeli-ynab-updater` to use `israeli-bank-scrapers@next` instead of a fixed version?

**Comment by eshaham** [comment]
@ifeins just updated `israeli-ynab-updater` to use 0.7.0.
Interesting idea to use `israeli-bank-scrapers@next`, though I would use `israeli-bank-scrapers@latest` - @esakal wdyt?

**Comment by esakal** [comment]
> Alternatively is it possible to change israeli-ynab-updater to use israeli-bank-scrapers@next instead of a fixed version?

the `latest` and `next` are only npm tags used during install/update, in `package.json` and `package-lock.json` it registers the actual value the tag referenced to at that point. So basically you cannot change it to use `next`. I might be missing something, wdyt?

**Comment by eshaham** [comment]
no, you're right... 😞 
I guess we will need to remember taking the latest release as soon as possible (or when @dependabot-bot recommends it)
