### ISSUE TITLE
Add an option to ignore transactions with 0 amount

### ISSUE THREAD

**Issue by eshaham** [eshaham/israeli-bank-scrapers#31]
In some of the banks they show transactions with 0 amount - these should not be returned if this option is specified.

**Comment by tounano** [comment]
@eshaham Why not?

From book keeping / business stand point these have a meaning. I understand why for personal use, these are irrelevant. But for accounting automation these transactions are important.

**Comment by eshaham** [comment]
@tounano absolutely agree, what I had in mind is to make this optional.
I've updated the issue title and description accordingly.
