### ISSUE TITLE
Discount scraper stopped working

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#322]
Discount scraper fails with the following error: `Login failed with UNKNOWN_ERROR error`

**Comment by brafdlog** [comment]
The issues is that the expected success url after login is: `https://start.telebank.co.il/apollo/core/templates/default/masterPage.html#/MY_ACCOUNT_HOMEPAGE`

But the actual url is `https://start.telebank.co.il/apollo/core/templates/RETAIL/masterPage.html#/MY_ACCOUNT_HOMEPAGE`

I see that discount have updated their ui and I assume in this new ui the success url changed

**Comment by brafdlog** [comment]
Created a pr to fix #323

**Comment by esakal** [comment]
pr #323 merged, as mentioned in the PR It might take time until it will be released as official latest. in the meanwhile feel free to pull the `next` tag from npm:
```
npm i israeli-bank-scrapers@next
```
