### ISSUE TITLE
Upgrading from version 0.6.9 to 0.8.0 breaks the visa cal scraper

### ISSUE THREAD

**Issue by brafdlog** [eshaham/israeli-bank-scrapers#324]
With version `0.6.9` the visa cal scraper works correctly.
After upgrading to version `0.8`, visa cal scraping fails with the following error message:
`invalid json response body at https://restservices.cal-online.co.il/Cal4U/CalAuthenticator reason: Unexpected token < in JSON at position 0`

**Comment by esakal** [comment]
hi @brafdlog,
is this still relevant? I managed to scrape 2 different users with 4 accounts (cards) total.
also, our source code doesn't include `CalAuthenticator` term. It might be an internal redirect tho.

let me know if it still happens

**Comment by brafdlog** [comment]
After installing the @next version it works. Closing the issue.
Thanks
