### ISSUE TITLE
Leumi Card renamed to MAX

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#341]
Just see in the URLs and so...

**Comment by adiohana** [comment]
Hi @baruchiro 
I would like to contribute to this project.
any chance for some more details about this issue?

**Comment by baruchiro** [comment]
This project uses the old name of "LeumiCard", and "LeumiCard" changed their name to "Max", so you need to change all "Leumi Card" in this project to "Max".

I'm just waiting to hear @eshaham 's opinion, but I think you can start because I don't see a reason for it to be a problem.

**Comment by eshaham** [comment]
> I'm just waiting to hear @eshaham 's opinion, but I think you can start because I don't see a reason for it to be a problem.

Totally makes sense

> Hi @baruchiro
I would like to contribute to this project.
any chance for some more details about this issue?

PR welcomed

**Comment by adiohana** [comment]
@eshaham @baruchiro 
Just created my first PR :]
I have a strong background in financial web-scraping (mainly in US market) and I just heard about this cool project; I will definitely contribute more in the future.

**Comment by eshaham** [comment]
merged 👍
