### ISSUE TITLE
Add loan account to returned entities

### ISSUE THREAD

**Issue by adiohana** [eshaham/israeli-bank-scrapers#349]
In general, I think that users would like see their loan accounts (regular loans, mortgages, etc.)
This will be useful for many use cases.

**Comment by adiohana** [comment]
@baruchiro @eshaham 
what do you think? can we start implement this?

**Comment by baruchiro** [comment]
First of all, to not mislead you, I'm not a maintainer of this project.

Also, I don't have loans and mortgages, so I don't know what is needed.

And see #76.

**Comment by eshaham** [comment]
@adiohana while this is very important financial info, it won't be relevant to most users of this repo IMO. We will find it is very hard to add this info across the different scrapers.
There are many more basic things we need to do across the different scrapers, like more basic information about the checking account.
Let's skip this for now until the repo is much more mature.
Closing for now.

**Comment by adiohana** [comment]
@eshaham thanks for the input.
do we have the list of essential info we want to add across scrapers? I will be happy to do some work

**Comment by baruchiro** [comment]
I think this is the object we want to recive from each account:

https://github.com/eshaham/israeli-bank-scrapers/blob/88bd7b2a5a0175086c988b68345d0c6f7f3e0773/README.md#L73-L96
