### ISSUE TITLE
Missing unionbank

### ISSUE THREAD

**Issue by dratler** [eshaham/israeli-bank-scrapers#364]
Hi @eshaham ,
You are missing unionbank (url : https://www.unionbank.co.il/igud/homepage/).
We at #Intuit would like to contribute to this effort.
@kalinoy and @shanigad from #Intuit.

**Comment by eshaham** [comment]
@dratler PR welcomed, please follow the [contribution guide](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md)
