### ISSUE TITLE
Mizrahi fetchData not working

### ISSUE THREAD

**Issue by SafiX** [eshaham/israeli-bank-scrapers#365]
Trying to simply get data with the default example.

Mizrahi.js - 

`const request = await this.page.waitForRequest(TRANSACTIONS_REQUEST_URL);`

The request that is being waited for already happens in the 'postAction' step, so this line will time out.

**Comment by SafiX** [comment]
I've fixed it locally if you're interested. Currently I don't have permissions...

**Comment by esakal** [comment]
@SafiX hi :) nice to e-meet you. Feel free to contribute. You can fork this repository and create a PR from your fork into this repository. see [this](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) article.

I hope this help
Eran

**Comment by SafiX** [comment]
Hi, so after changing the default landing page after login, I cant reconstruct the issue anymore. Closing the issue.
