### ISSUE TITLE
Add more test coverage

### ISSUE THREAD

**Issue by dratler** [eshaham/israeli-bank-scrapers#368]
We would like to add more test coverage to this project.
@kalinoy , @shanigad , @dudiventura , @NoamGoren and @dratler

by #Intuit

**Comment by eshaham** [comment]
hey @dratler 
It's great to hear you guys want to help.
We definitely need better test coverage.
What do you have in mind?

**Comment by dratler** [comment]
Well I have talk to the team.
we would like to test i\o and also to add some unit tests
