### ISSUE TITLE
Visa cal not working

### ISSUE THREAD

**Issue by blocka** [eshaham/israeli-bank-scrapers#372]
The authentication endpoint is failing with a 503. I couldn't find any information about the REST api online (https://restservices.cal-online.co.il), so I'm guessing this a completely undocumented api, that may have been blocked?

**Comment by eshaham** [comment]
@blocka not sure, just ran it now and it's working for me.
can you check again? if not working, do you manage to login into the website on the browser?

**Comment by blocka** [comment]
I can log into the website fine. I haven't yet tried from the scraper, but a manual HTTP request (eg., using postman), still fails:

```
curl -X POST \
  https://restservices.cal-online.co.il/Cal4U/CalAuthenticator \
  -H 'content-type: application/json' \
  -d '{"username": "USERNAME", "password": "hunter2"}'
```

**Comment by eshaham** [comment]
@blocka you're referencing an old version of the visacal code - see here:
https://github.com/eshaham/israeli-bank-scrapers/issues/324

seems like the URLs have changed.
FYI, they are indeed undocumented.

**Comment by eshaham** [comment]
closing this issue for now

**Comment by blocka** [comment]
Thanks...upgrading fixed the problem :man_facepalming: 
If you can point out to me the documentation though, that would be appreciated...I could not find it, and putting the URLs into google didn't come up with anything.
