### ISSUE TITLE
Ubuntu - Unable to open X display.

### ISSUE THREAD

**Issue by LevBuchel** [eshaham/israeli-bank-scrapers#387]
Hello and thank you for your work on this open source project!
I have ran into an issues.
I am using Ubuntu 16.04 and i have installed all dependencies as required in the puppeteer guide.
When testing the scraper from my own application i am getting a response with the following error:
> "scraping failed for the following reason: Failed to launch the browser process!","[27096:27096:0318\/064133.839878:ERROR:browser_main_loop.cc(1512)] Unable to open X display.","","","TROUBLESHOOTING: https:\/\/github.com\/puppeteer\/puppeteer\/blob\/master\/docs\/troubleshooting.md",""

After going through similar issues, it seems that i have to set the `browser` option with `headless: true,` 
I can see that you have this option and the explanation is `"you can get browser diretly from puppeteer via puppeteer.launch() command"`.
Is there an example of how i should pass that `Browser` value? 

Do i pass it like so: 
`(async () => {return await puppeteer.launch({ headless: true, args: ['--no-sandbox'] })})(),`
or like this:
`browser: { headless: true, args: ['--no-sandbox'] }`

Which gives me the next error (for both options):
> "scraping failed for the following reason: this.browser.pages is not a function"

Maybe i am doing something else wrong..
Here is my code:
```
const { createScraper } = require('israeli-bank-scrapers');
// const { puppeteer } = require('puppeteer');

const credentials = {
    hapoalim: { userCode: 'test', password: 'test' },
    // hapoalimBeOnline: { userCode: '', password: '' },
    // leumi: { username: '', password: '' },
    // discount: { id: '', password: '', num: '' },
    // otsarHahayal: { username: '', password: '' },
    // max: { username: '', password: '' },
    // visaCal: { username: '', password: '' },
    // isracard: { id: '', password: '', card6Digits: '' },
    // amex: { id: '', card6Digits: '', password: ''},
    // mizrahi: { username: '', password: ''},
};

const startDate = new Date();
startDate.setMonth(startDate.getMonth() - 1);

const options = {
    companyId: 'hapoalim', // mandatory; one of 'hapoalim', 'hapoalimBeOnline', leumi', 'discount', 'mizrahi', 'otsarHahayal', 'visaCal', 'max', 'isracard', 'amex'
    startDate, // the date to fetch transactions from (can't be before the minimum allowed time difference for the scraper)
    combineInstallments: false, // if set to true, all installment transactions will be combine into the first one
    showBrowser: true, // shows the browser while scraping, good for debugging (default false)
    verbose: false, // include more debug info about in the output
    // browser: (async () => {return await puppeteer.launch({ headless: true, args: ['--no-sandbox'] })})(),
};

(async function() {
    try {
        const scraper = createScraper(options);
        const scrapeResult = await scraper.scrape(credentials);

        if (scrapeResult.success) {
            scrapeResult.accounts.forEach((account) => {
                console.log(`found ${account.txns.length} transactions for account number 
            ${account.accountNumber}`);
            });
        }
        else {
            throw new Error(scrapeResult.errorType);
        }
    } catch(e) {
        console.error(`scraping failed for the following reason: ${e.message}`);
    }
})();
```

**Comment by LevBuchel** [comment]
Ok, so i think i found the code (base-scraper-with-browser.js):
```
if (typeof this.options.browser !== 'undefined' && this.options.browser !== null) {
      this.browser = this.options.browser;
    } else {
      this.browser = await puppeteer.launch({ env, headless: !this.options.showBrowser });
    }
```
It seems that if the browser option was not set then it gets the headless value from  !showBrowser option.
Which means i have to pass showBrowser as false, which i did.
And i got this error:
`"scraping failed for the following reason: GENERIC"`

Regardless, maybe passing the browser option causes an issue?

**Comment by esakal** [comment]
Hi @LevBuchel, sorry for not replying sooner. I haven't seen the email notification. Do you still experience this issue?
You wrote that you set all the relevant puppteer dependencies but this is something that happens automatically when you install dependencies so I'm not sure if you are trying to use the core version or the default version.

To answer your first question, assuming you are using the default version, all you need to do is to pass `showBrowser: false` in the options and we it will set the `headless` property of puppteer to `true` - but I see that you have tried this one already.

Can you share console log and remove sensitive information?

**Comment by LevBuchel** [comment]
Hello @esakal thank you for your reply.
I am using the default version.
Yes i have passed `showBrowser: false` and the error i am getting is:
```
response =  ["scraping failed for the following reason: GENERIC {\"success\":false,\"errorType\":\"GENERIC\",\"errorMessage\":\"text is not iterable\"}"]
```

When `showBrowser: true` i am getting the next error:
```
response =  ["(node:8443) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!","[8453:8453:0415\/102921.646837:ERROR:browser_main_loop.cc(1512)] Unable to open X display.","","","TROUBLESHOOTING: https:\/\/github.com\/puppeteer\/puppeteer\/blob\/master\/docs\/troubleshooting.md","","    at onClose (\/var\/www\/client\/node_modules\/puppeteer\/lib\/Launcher.js:750:14)","    at Interface.helper.addEventListener (\/var\/www\/client\/node_modules\/puppeteer\/lib\/Launcher.js:739:50)","    at emitNone (events.js:111:20)","    at Interface.emit (events.js:208:7)","    at Interface.close (readline.js:368:8)","    at Socket.onend (readline.js:147:10)","    at emitNone (events.js:111:20)","    at Socket.emit (events.js:208:7)","    at endReadableNT (_stream_readable.js:1064:12)","    at _combinedTickCallback (internal\/process\/next_tick.js:139:11)","(node:8443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)","(node:8443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."]
```

This is a full copy of the console log.

**Comment by esakal** [comment]
Do you have a way to debug it? if so see the contributing.md file it contains infromation how to run tests.

**Comment by LiranBri** [comment]
I also get this `GENERIC: text is not iterable` error from bank hapoalim scraper, but its not consistent
