### ISSUE TITLE
Question about visa-cal

### ISSUE THREAD

**Issue by JavierChames** [eshaham/israeli-bank-scrapers#399]
Hello al i would like to ask a question about Visa cal scrapper,i use raspberry pi for this great project,for other acoounts like pohalim or isracard all works ok somwhow,i don't understand why,Visa cal stack,i i  dont know where,the same code in the PC works ok,some clue what or where to inspect?
Thanks

**Comment by esakal** [comment]
can you send a print screen of the error stack / message?

**Comment by JavierChames** [comment]
Hi, i don't have actually screenshot...
according the code...i have a main async function

async function getdata() {

}

somehow the function doesn't end.. I mean, stuck
I have some console.log of the data that appears in the console, but then something is stuck and I don't know what-as mentioned its in raspberry pi

**Comment by esakal** [comment]
Hi,
Bank Hapoalim and Isracard scrapers are using puppeteer to scrape the data. Visa Cal doesn't. I understand that you have access to console log. Please share them here and remove sensitive data.

You can also add your own custom comments to figure out where it get stuck. Once you find the relevant piece of code share it here and we will try to assist

Eran.

**Comment by JavierChames** [comment]
Hello
so-these is my code(please don't jug me for code review...

const puppeteer = require('puppeteer');
const { createScraper } = require("israeli-bank-scrapers");
//const sheetservice = require("./Sheets/AddToGoogleSheet");
const file_name = "./cal.txt";
let moment = require('moment');
//const dayBacksToShow = 2;
const dayBacksToShow = new Date().getDate();
let myCredentials = read_crendentials(file_name);
const mycard = myCredentials[2]
let amount;
let today1 = moment();
let startDateQuery = today1.subtract(dayBacksToShow, 'days').format('YYYYMMDD');
let os = require('os');
let arrayAccount = [];

function read_crendentials(type) {
  let fs = require("fs");
  let text = fs.readFileSync(type).toString("utf-8").split("\r");
  text = text.map(x => { return x.replace(/(\r\n|\n|\r)/gm, "") });
  return text;
}

const credentials = {
  username: myCredentials[0].split("\r")[0].toString(),
  password: myCredentials[1].split("\r")[0].toString(),
};



function shortDate(date) {
  date1 = new Date(date[0]);
  year = date1.getFullYear();
  month = date1.getMonth() + 1;
  dt = date1.getDate();
  if (parseInt(date[1].split(":")[0]) > 15) {
    dt += 1;
  }

  if (dt < 10) {
    dt = "0" + dt;
  }
  if (month < 10) {
    month = "0" + month;
  }
  return dt + "-" + month + "-" + year;
}

 

async function getdata() {
	try{
	if (os.type() == "Linux") {
      browsertype = await puppeteer.launch({ executablePath: 'chromium-browser' })
      showBrowser = false
    }
    else {
      browsertype = null
      showBrowser = true
    }

    const options = {
      companyId: "visaCal", // mandatory; one of 'hapoalim', 'leumi', 'discount', 'mizrahi', 'otsarHahayal', 'visaCal', 'leumiCard', 'isracard', 'amex'
      startDate: "" + startDateQuery + "", // the date to fetch transactions from (can't be before the minimum allowed time difference for the scraper)
      combineInstallments: false, // if set to true, all installment transactions will be combine into the first one
      showBrowser: showBrowser,// shows the browser while scraping, good for debugging (default false)
      verbose: true, // include more debug info about in the output
      browser: browsertype// optional option from init puppeteer browser instance outside the libary scope. you can get browser diretly from puppeteer via `puppeteer.launch()` command.
      // executablePath: string // optional. provide a patch to local chromium to be used by puppeteer. Relevant when using `israeli-bank-scrapers-core` library
    };
    const scraper = createScraper(options);
    const scrapeResult = await scraper.scrape(credentials);
	
	
	
	
  //try {
   

    if (scrapeResult.success) {
      scrapeResult.accounts.forEach(account => {
        
        let currectAccount = account.accountNumber
        if (account.txns.length && account.txns.length >= 1 && (currectAccount == mycard)) {
          console.log(
            `found ${account.txns.length} transactions for account number ${currectAccount}`
          );
          ;
          account.txns.forEach(transaction => {
            let chargedAmount = transaction.chargedAmount;
            let res = transaction.date.split("T");
            let date = shortDate(res);
            if (transaction.memo != null) {
              descriptionMemo = transaction.memo;
            } else {
              descriptionMemo = "";
            }


            // if (transaction.memo != "זיכוי") {
            //   if (Math.abs(chargedAmount == 0)) {
            //     amount = 0;
            //   }
            //   else {
            //     amount = Math.abs(chargedAmount);
            //   }
            // }
            // else {
            //   amount = -Math.abs(chargedAmount);
            // }
            if (transaction.chargedAmount > 0) {
              amount = -Math.abs(chargedAmount);

            }
            else {
              amount = Math.abs(chargedAmount);
            }
            if (transaction.type === "normal") {
              arrayAccount.push({
                תאריך: date,
                פירוט: transaction.description,
                "פירוט מורחב": descriptionMemo,
                סכום: amount,
              }
              );
            }

            if (
              transaction.type === "installments") {
              arrayAccount.push({
                תאריך: date,
                פירוט: transaction.description,
                "פירוט מורחב": descriptionMemo,
                סכום: Math.abs(amount),
                "תשלום מתוך": transaction.installments.number,
                "סהכ תשלומים": transaction.installments.total,
                סהכ: Math.abs(transaction.originalAmount)
              });
            }
            console.log(
              "Date: " +
              date +
              " Details:" +
              transaction.description +
              " Amount:" +
              amount
            );
          });
   }
      });
    } else {
      throw new Error(scrapeResult.errorType);
    }
  } catch (e) {
    console.error(`scraping failed for the following reason: ${e.message}`);
	getdata()
  }
  }

getdata();


what is get is:
![image](https://user-images.githubusercontent.com/12410221/79669763-974af080-81c6-11ea-92de-7264f50ac826.png)

but the script doesn't finish(end)....
i run it as mentioned from raspberry pi 3(all the other files I sue-hapolaim and isracard works ok)

**Comment by esakal** [comment]
I'm not sure if this is causing the problem but please try to change the call `await` before the `getdata()`.
so the last line will be `await getdata();`

if it doesn't compile, try
```
(async function() {
    await getdata();
})();
```
let me know what happended

**Comment by JavierChames** [comment]
unfurntally , no change even when adding 
(async function() {
    await getdata();
})();

the reason I call the main function to collect data after the error is to try again if I fail to scrap, for Hapoalim/Isracard it works perfects..
also in my pc, all works ok-maybe its something related to environments?

**Comment by JavierChames** [comment]
I found the solution(workaround?)
I added just before the main function finish:
await browsertype.close();
and then the scrip finish...

**Comment by esakal** [comment]
Hi,
Actually is sound like the solution you were looking for. I have missed it when I read your code but you do need to close connections. In some OS there are guards that can handle memory issues and force script to complete but maybe in raspberry pi it does wait for someone to close that connection.

Nice catch!

but regardless, you should imo use await with `getdata` because otherwise you are not waiting for it to complete. 

I'm glad you found the solution you were looking for. If it works for you and you don't have anything else in that matter please close the comment.

**Comment by JavierChames** [comment]
Solution found, in Raspberry pi need to close the browser connection at the end...
Issue closed, Thanks @esakal  for the support
