### ISSUE TITLE
possible problem with union bank scraper

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#415]
Hi @dratler 
Line 168 doesn't seems correct.

https://github.com/eshaham/israeli-bank-scrapers/blob/a983b8b7741271d5f6797761dd2099ba447302b5/src/scrapers/union-bank.js#L167-L170

Since `elementPresentOnPage` returns a `boolean`, checking `offsetParent` will return `undefined` and the condition will always be true.

https://github.com/eshaham/israeli-bank-scrapers/blob/a983b8b7741271d5f6797761dd2099ba447302b5/src/helpers/elements-interactions.js#L36-L38

wdyt?

**Comment by dudiventura** [comment]
Hi @esakal
Thank you for brining it up, you are right.
It something we started to check during the development and didn't noticed that we left it like that which is wrong.

I'm deploying a fix to this function now.
