### ISSUE TITLE
Passing args to puppeteer launch method 

### ISSUE THREAD

**Issue by ocherfas** [eshaham/israeli-bank-scrapers#419]
In my project, I run the scrapper from inside a docker container, and I want to make is as easy as possible. To prevent some issues that come up on the container and puppeteer, I need to pass an argument to the underline chrome process `--no-sandbox`.
I do not see any option to pass it through the api currently.
I guess that the required code change would be under https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/base-scraper-with-browser.js, when calling `puppeteer.launch` to pass an args variable.
I would be happy to work on a solution if you would direct me to how do you think the args should be passed from the api.

**Comment by esakal** [comment]
Hi @ocherfas,
I think the API already support your use-case. We are allowing to pass the browser instance exactly for that purpose. Can you try in your code to provide the following browser as part of the `options` object?
```
const options = {
   // what ever you currently sending
   browser: await puppeteer.launch({
         // provide here the relevant arguments.
      });
}.
Just make sure that the puppeteer you are using is the same major version we are using (or ideally the same version x.y.z) so the api calls we execute on the puppeteer will work.

Let me know if it worked for you.

**Comment by ocherfas** [comment]
Seems to work thanks!. 
Maybe would be nice to add documentation for it. What do you think?

**Comment by ocherfas** [comment]
Actually because I got into some issues for handling the browsing instance (for example closing the browser instance), I still think the better solution would be to pass extra arguments for the underline instance.
In the package, the puppeteer instance is handled correctly. As a user I would much rather use that handling and just pass arguments.

**Comment by esakal** [comment]
@eshaham wdyt?

**Comment by eshaham** [comment]
I think it's a good idea to add the option to pass arguments to the puppeteer instance rather than having to maintain it by yourself.
@ocherfas PR welcomed!

**Comment by esakal** [comment]
@ocherfas Hi! I created a PR to allow passing arguments to the puppeteer lunch command.  Feel free to track the merge status there
