### ISSUE TITLE
Visa cal issue-probably related to site(not sure where/what is the problem)

### ISSUE THREAD

**Issue by JavierChames** [eshaham/israeli-bank-scrapers#447]
since today I get this message for visa_cal
scraping failed for the following reason: UNKNOWN_ERROR No token found in authResponse: "אנו מתנצלים, עקב תקלה לא ניתן לבצע את הפעולה כעת.|ניתן לנסות שנית במועד מאוחר יותר"

**Comment by JavierChames** [comment]
I found the issue, my password expired and needed to change it
needed a better way to detect it...
![image](https://user-images.githubusercontent.com/12410221/83349822-60790600-a340-11ea-960f-19b609b7c3be.png)

**Comment by esakal** [comment]
Hi,
It happens frequently as it is not easy to simulate change password scenario. Next time it happens to you if you can create a PR with a fix it would be great!

Comment on this issue if you need further assistance.

**Comment by orzarchi** [comment]
@JavierChames I made a PR for this issue #461 🍾
