### ISSUE TITLE
Problem with OtsarHahayal from npm registry

### ISSUE THREAD

**Issue by baaraak** [eshaham/israeli-bank-scrapers#457]
Hi,
I have a weird bug when I'm trying to use this package and install it from npm (`npm install israeli-bank-scrapers`)
I get:
```
$ scraping failed for the following reason: GENERIC
```
I'm using valid credentials and I'm using the same code from the README file.
When I set `showBrowser: true` this what I get.
![Screen Shot 2020-06-08 at 23 59 03](https://user-images.githubusercontent.com/16448454/84181734-055ab800-aa92-11ea-8a13-3eaa9ec3b9a7.png)

Then I tried to clone this repo and used it locally (`npm run build && npm link`) and then everything started to work.
I have no idea what is causing it, maybe the version on npm is not up to date?

Also, thank you for this great package!

**Comment by esakal** [comment]
please try `npm i israeli-bank-scrapers@next` and let me know if it works. If so we should ask @eshaham to release new official version

**Comment by baaraak** [comment]
Working! 
Thanks... 👍 👍

**Comment by esakal** [comment]
Yesh!
@eshaham can you please release a new version and then close this one?

**Comment by esakal** [comment]
@eshaham please close this one once you release a new official version

**Comment by eshaham** [comment]
@esakal @baaraak done
