### ISSUE TITLE
Support Typescript - Contributors Call To Action

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#487]
Hi All,

As you probably saw in the last few months we worked on a PR that will add Typescript support to our codebase. All the companies and utils were migrated to use Typescript in this pr #404.

# Call to action - testing all companies with the typescript support

> We should try and finalize it this week so we will be able to start August with static type checks guarding us and letting us be more relaxed during this full-parenting-month.

**WE NEED YOUR HELP!** making sure all the companies work as expected. 

The table below list all the 
I mentioned below the creator of each company, even if you are not a creator if you managed to test more companies please add a comment and I will update the table accordingly. 

|  Company | Creator  | Tested by 
|---|---|---|
|  Bank Hapoalim | @sebikaplun  | @esakal  |   
|  Leumi Bank | @esakal  |  @esakal, @baruchiro    |   
|  Discount Bank |   | @brafdlog  |   
|  Mizrahi Bank |  @baruchiro  | @baruchiro  |   
|  Otsar Hahayal Bank |  @matanelgabsi    |   |   
|  Visa Cal |   @nirgin   | @brafdlog,  @esakal    |   
|  Max |   |   @esakal, @baruchiro   |   
|  Isracard |   | @baruchiro, @esakal   |   
|  Amex |  @erezd   |  @esakal  |   
|  Union Bank |   @dratler,@kalinoy,@shanigad,@dudiventura and @NoamGoren  |   |   
|  Beinleumi | @dudiventura   |   |   

(*) Hopefully at least two contributors will confirm each company, although one will be accepted as well.

## Testing steps
> IMPORTANT NOTICE: the test folder was moved from `./tests` into `src/tests` to meet the Typescript requirement that everything is under the `src` folder. Once you checkout the Typescript branch you will need to re-create that file (explained in the guide below).

**Please use the following guide to test the companies that you have and drop a comment with the list of companies you tested. If it fails on one or more of them add the compilation error in the comment.**

- [ ] Make sure you don’t have any uncommitted changes.
- [ ] Check out the `typescript` branch
```
git pull
git checkout typescript
```
- [ ] delete `node_modules` folder 
- [ ] install dependencies `npm install`
- [ ] build the repo and make sure you don’t get any Typescript compile errors `npm run build`
- [ ] create the tests configuration file with your credential. Duplicate file `./src/tests/tests-config.tpl.js` -> `./src/tests/tests-config.js` 
- [ ] assign a valid path in the test configuration file under `excelFilesDist` property.
- [ ] add your credentials in the test file.
- [ ] run the tests `npm run test`

**Acceptance criteria:**
The library builds successfully 
All the companies you have created a valid excel file (meaning all the fields you expect to see there actually exist).

---

Thank you all for helping with this one. We hope the Typescript support will let us do great things with this library.

@eshaham, @esakal

**Comment by baruchiro** [comment]
I have a Mizrahi, Max, Leumi, Isracard. I can test these all.

**Comment by brafdlog** [comment]
I will test discount and visa cal

**Comment by brafdlog** [comment]
Checked discount and visa cal. Build passes and scraping works. As far as I can tell, looking good

**Comment by esakal** [comment]
Hi All
@brafdlog thanks! I will update the table above

@baruchiro thanks! the date is more like wishful thinking :) if you can test Max, Leumi and Isracard earlier and later handle Mizrahi that would be great, but obviously, whenever you can test it that would be great :) 

@eshaham can you pin this issue in the issues dashboard?

**Comment by baruchiro** [comment]
@esakal @eshaham You still have the old `tests` folder with `REAMDE.md` and `.gitignore`

**Comment by esakal** [comment]
A short update. I pushed a commit that merge latest changes from master and also revert the error status values to match the ones we are currently sending to preserve backward compatibility with them.

https://github.com/eshaham/israeli-bank-scrapers/pull/404/commits/cf92390be739dbe3cc6e140c9ece9ad967e4f95e

it is pending a review of @eshaham but if you will run the code you will already test it with those changes 👍

**Comment by baruchiro** [comment]
Tested on f784f7b9f20272d45b23f02d6d9b55680a87dea8:

- `leumi`
    - Both `invalidPassword` and `fetchTransactions` tests passed.
    - I think the `fetchTransacvtions` failed if `invalidPassword` is `true`. wired.
- `max` both passed
- `isracard` 
- `mizrahi`: waiting for 
==== My Windows is stuck, I have to restart=====

**Comment by esakal** [comment]
@baruchiro thanks, I will add it to the summary above.
Note regarding Isracard that it happens also in master so I'm going to open an issue specific for that and we can handle it separately. 

![image](https://user-images.githubusercontent.com/4751797/89033399-5e7ef380-d33f-11ea-9261-a938a48cbfe5.png)

**Comment by esakal** [comment]
retested the following with latest merge:
* Visa cal
* max
* isracard
* hapoalim
* leumi

**Comment by esakal** [comment]
@matanelgabsi, @dratler,@kalinoy,@shanigad,@dudiventura and @NoamGoren - Any chance you can run the tests to complete the remaining scrapers?

Thanks!
Eran

**Comment by esakal** [comment]
@eshaham please run tests as well and review latest changes due to merging from master and the fix of Mizrahi

**Comment by baruchiro** [comment]
**Mizrahi**, **Max**, **Isracard** and **Leumi** tested on 27a194ca313fde12ebf15a1c2d0f71350fe933e1, but I can't find the output CSV (also in the previous test I did not see, I forgot to search it).

**Comment by esakal** [comment]
@baruchiro I found the output csv of the companies I tested.  Can you make sure the field `excelFilesDist` has valid path?

```
companyAPI: { // enable companyAPI to execute tests against the real companies api
    enabled: true,
    excelFilesDist: '', // optional - provide valid path to save scraper results (csv format)
    invalidPassword: false, // enable to execute tests that execute with invalid credentials
  },
```

**Comment by esakal** [comment]
@brafdlog Hi, any chance you run your tests again with latest merges from master into this branch?

**Comment by brafdlog** [comment]
Checked visa cal and discount again. Looking good

**Comment by baruchiro** [comment]
@esakal Tested with csv output, see my fix #502

**Comment by esakal** [comment]
@brafdlog @baruchiro  thanks!

@eshaham how do you want to proceed? we confirmed 8 out of 11 companies, and the remaining three passes build checks but  were not tested by contributors that actually has those companies. Do you want to continue waiting or to merge it and handle issues if raises later as new PRs?

**Comment by eshaham** [comment]
@esakal I think we should carry on, no need to block forever
we want to see this PR merged

**Comment by esakal** [comment]
Hi All,
We are now type safe :) Thanks all for your patient waiting for the Typescript support.

If you encounter any issues feel free to open issues and I will try to assist.

Have a great weekend

**Comment by baruchiro** [comment]
Hooray!!

@brafdlog

**Comment by eshaham** [comment]
Great job!!!!
this is so awesome!

**Comment by baruchiro** [comment]
Hi, looking at the latest version [v0.9.1](https://github.com/eshaham/israeli-bank-scrapers/tree/v0.9.1), it is JS version.

When do you plan to publish a new version?

I need it also because the Mizrahi is broken in 0.9.1

**Comment by eshaham** [comment]
@baruchiro I messed up
meant to do it a few times already, but apparently each time something distracted me and then I forgot 🤦 
anyway, v1.0.0 is now released 🥳 
cc @esakal
