### ISSUE TITLE
Scraper Microservice

### ISSUE THREAD

**Issue by omercnet** [eshaham/israeli-bank-scrapers#505]
Has anyone implemented a microservice for this package?
Not everyone writes in nodejs, making this package available over REST API microservice would make it possible to use this :)

Will be happy to create something that builds off the SCRAPERS object

**Comment by omercnet** [comment]
created https://github.com/omercnet/israeli-bank-scrapers-api

hope this helps someone besides me :)

**Comment by eshaham** [comment]
@omercnet thanks for sharing.
This is a much-needed service, and I bet it may also have business opportunities (the main problem is that at scale it might get blocked by banks, and whoever implements it will need to take it under considerations).
For personal usage which targets those who don't code in node.js this sounds like a good idea.
Let us know when this project is more mature (has a proper readme, everything works) and we will add it to the known projects sections 😄 
Closing this issue for now.

**Comment by omercnet** [comment]
I've been actually using it myself for testing as I was adding the enhancement in #509 
I'd be happy to propose a PR to this repo that includes the server as part of the library to help development as well as standalone container that can be used as a standalone microservice 

wdyt?
