### ISSUE TITLE
Bank Yahav Scraper?

### ISSUE THREAD

**Issue by tomreposify** [eshaham/israeli-bank-scrapers#510]

**Comment by baruchiro** [comment]
Hi, you're welcome to develop it yourself.

Please look at the other scrapers as an example, and start to find the CSS selectors and so on for Bank Yahav.

I'm following this issue now, and also @eshaham  and @esakal were always here for me when I needed a consultation.

Try to get started and any question or dilemma share with us here.

**Comment by eshaham** [comment]
@tomreposify one of the limitations of this project is that we don't actually have access to all banks/credit card providers, so we need help from the community to cover all of them.
If you're up for it, see [contributing doc](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md) to get started and feel free to ask questions here.
