### ISSUE TITLE
Next version automatic deployment is broken and needs new NPM credentials

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#525]
@eshaham it seems that something happened with the authentication token used to deploy automatically the next version to npm. see the [failure results] (https://github.com/eshaham/israeli-bank-scrapers/runs/1235168325?check_suite_focus=true)

Can you please update the environment authentication token to resolve it? 

you can then click on the re-run jobs to verify that it works.
![image](https://user-images.githubusercontent.com/4751797/95652993-d6b32380-0afd-11eb-819c-568967e0d34d.png)

![image](https://user-images.githubusercontent.com/4751797/95652970-a1a6d100-0afd-11eb-9c6a-3a769ea6c4e1.png)

**Comment by eshaham** [comment]
@esakal so I think I solved the auth issue but broke versioning
we probably need to run `npm version` as a build step to add the dev prerelease build number somehow

**Comment by esakal** [comment]
@eshaham the problem with npm version is that it commits it to github, it also doesn't use dirt (random value) so if we will not push it to master it will try to create the same version every time.

``` npm version prerelease --preid=next```

Why not reverting to what we previously had? what was the problem with that code? https://github.com/eshaham/israeli-bank-scrapers/blame/9e9eda9c3a711786cabc74f16fe2677ce7574243/.github/workflows/prerelease.yml

**Comment by baruchiro** [comment]
There are a few issues and PRs about this problem, so I can't find the updated one.

But the `next` release is still broken.

Also, why not publish another **release**?

**Comment by eshaham** [comment]
@baruchiro I just triggered another next release and managed to run it nicely.
can you check if it's working for you?
will prepare an official release now.

**Comment by baruchiro** [comment]
Yes, it working!

But if you're releasing a new stable release now, I will wait for that.

Thanks!

**Comment by eshaham** [comment]
@baruchiro just did 💪
