### ISSUE TITLE
Start work with Banks API?

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#528]
#### Discont

https://www.openbanking.co.il/open-banking/discount-api-catalog

Seems they have an API to fetch the data we need. They require registration.

#### Isracard

https://devportal.isracard.co.il/isracard/prod/

**Comment by esakal** [comment]
it would be amazing! but... at the moment they provide api of open banking only to companies not to individuals. 
> הפלטפורמה מיועדת לחברות, עסקים וסטארטאפים, שמעוניינים לפתח מוצרים ושירותים חדשניים עבור לקוחות הבנק, או עבור חברות שמעוניינות לייעל תהליכי עבודה פנימיים תוך יצירת ממשק ישיר לחשבונן בבנק.
המעוניינים לעשות שימוש בפלטפורמת הבנקאות הפתוחה של דיסקונט ייבחנו בהתאם להצעת הערך שהחיבור לבנק יוכל להניב עבורם ועבור לקוחות דיסקונט.

**Comment by eshaham** [comment]
I definitely love where this is going - open banking will eventually make this project obsolete.
But for now, they don't allow individuals to access the API, hoping they will change the policy soon (if anyone here got connections, this would be the time to talk to them).
Closing this for now.

**Comment by baruchiro** [comment]
I have to say that I think this project will still be relevant even with Open Bank, since this project exposes one interface for all the banks...

**Comment by baruchiro** [comment]
חוק הבנקאות הפתוחה עבר בחוק ההסדרים.
I suggest starting to think about if and how this library will continue.
Let's think, what we will get with **open banks**?
We will get more secured account analytics apps, but is the regular person will be able to implement a private app itselfs?
I think no.

I see two points-
1. Be the library for individuals who will not work for getting approval and authenticate with the bank, just for a script.
2. Be an SDK for all the other apps will become (individual/enterprise).
