### ISSUE TITLE
Question: help with Bank Yahav

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#540]
Hi,
I'm trying to make a new Bank Yahav scrapper but I lack UI experience... For now, I managed to login, but I cannot jump to the page where the transactions can be extracted (/main/accounts/current/).

The home page is at `https://digital.yahav.co.il/BaNCSDigitalUI/app/index.html#!/main/home`. Changing it manually in the browser to `https://digital.yahav.co.il/BaNCSDigitalUI/app/index.html#!/main/accounts/current/` does nothing... *something* happens when clicking in the link.

I tried to use the `navigateTo` and later `clickButton`, and `clickLink` without success so probably I'm not creating correctly the selector.

I added a screenshot of the chrome screen... Someone can help with the selector?

![yahav1](https://user-images.githubusercontent.com/754466/99831255-789b4680-2b67-11eb-807f-f9734a195e22.png)

**Comment by esakal** [comment]
Hi @gczobel checkout out for references in the project like [this one](https://github.com/eshaham/israeli-bank-scrapers/blob/849f6d0497cd2829f2b8cb4f289d0f1138b3accc/src/scrapers/beinleumi.ts#L190)

try
```
await clickButton(page, 'a#[ui-sref="main.accounts.current"]);

// options a
  await waitUntilElementFound(page, 'some selector');

// options b - might be better
await waitForNavigationAndDomLoad(page);
```

Let me know if it helped :)

**Comment by gczobel** [comment]
It worked but I still have issues with other parts... I'm closing this and I'll open another one if I need more help.
Thanks!
