### ISSUE TITLE
Help: Selecting dates in Yahav Bank

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#542]
Hi,
I managed for now to login and extract the transaction on the Yahav Bank.
The only missing part is a way to select the transaction dates.

The date selector does not allow any text input, only mouse clicks. I don't see any easy way to use it... maybe you guys with more UI experience are able to help.

I attached two images showing the page structure and the complete HTML of the date selector.

Any help will be highly appreciated!

![dateselector](https://user-images.githubusercontent.com/754466/101259912-9e624700-3734-11eb-95db-faed1b9dcd65.png)
![dateselector2](https://user-images.githubusercontent.com/754466/101259916-a15d3780-3734-11eb-8454-b4d84eb2f6b3.png)

[dateselector_html.txt](https://github.com/eshaham/israeli-bank-scrapers/files/5647623/dateselector_html.txt)

**Comment by esakal** [comment]
Hi @gczobel,
From the snapshot provided you can easily call the method that the control call on close and thus bypassing the ui complexity.

use something like 
```
  await page.evaluate(_ => {
    // this will be executed within the page
   // TODO add here the call done to onClose
  });
```

![image](https://user-images.githubusercontent.com/4751797/101753808-bbec3380-3adb-11eb-8bd2-eb9e792066dc.png)

**Comment by gczobel** [comment]
Something like this?
  await page.evaluate(_ => {
    'currentAccount.onFromCalendarClose("01/09/2020")';
  });

**Comment by esakal** [comment]
yes that should work. did you try it?

**Comment by gczobel** [comment]
Yes... do nothing. I tried changing the value of the date in the component too... but nothing happens when the line is executed...

**Comment by esakal** [comment]
```
await page.evaluate(_ => {
currentAccount.onFromCalendarClose("01/09/2020");
});
```
In your code you wrap the command with ' which make it a string. I believe this is why it doesn't work for you. Try the code I wrote above.

Also, make sure that you pass the date in the same format they the actual site does. you wrote it in `dd/MM/yyyy`. I suggest you to set a breakpoint and check the value the way they do it, confirm the format and the separator sign.

**Comment by esakal** [comment]
@gczobel did it worked for you?

**Comment by gczobel** [comment]
Sorry, I was stranded abroad all this time without access to my github account.
No... the latest option didn't work... and I cannot find a way to change the dates.
I have zero web / puppeteer experience so I'll try to filter the dates programmatically.
