### ISSUE TITLE
Scraping current balance

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#547]
Following #546 PR where a new field named `balance` was added to the accounts as an optional field, whoever can add it to more companies and relate his/her PRs to this ticket that would be great.

https://github.com/eshaham/israeli-bank-scrapers/blob/556eba0adf0fed34e652a48ce67b1645221ef19c/src/transactions.ts#L3-L5

# Coverage
- [x] Bank Leumi
- [ ] mizrahi
- [ ] discount
- [ ] otsarHahayal
- [ ] leumiCard
- [ ] max
- [ ] visaCal
- [ ] isracard
- [ ] amex
- [ ] union
- [ ] beinleumi
- [ ] hapoalimBeOnline
- [ ] hapoalim

**Comment by LiranBri** [comment]
I created a PR for getting the balance of Beinleumi bank
https://github.com/eshaham/israeli-bank-scrapers/pull/605
