### ISSUE TITLE
Not all tansaction get on Visacal

### ISSUE THREAD

**Issue by moshe212** [eshaham/israeli-bank-scrapers#550]
I do not get my transaction from 2021 at all.
I pay on 10.01.2021 and i do not see this at all..

**Comment by baruchiro** [comment]
More than that, I see the `max.ts` and `visa-cal.ts` shared the code related to `startMoment`, so you need to find where it different.

I guess it something related to the scraping itself.

**Comment by esakal** [comment]
@moshe212  does it still happen to you? if so, can you write here the version you are actually using (either from package.json or package-lock.json) 

also what do you get? empty array or an error?

**Comment by esakal** [comment]
@moshe212 let me know if it still happens. If it does, share more logs / information so we will be able to try and assist
