### ISSUE TITLE
MAX login is broken (via  israeli-bank-scapers-desktop)

### ISSUE THREAD

**Issue by MosheL** [eshaham/israeli-bank-scrapers#553]
I have an username/password for max.
the hidden browser is going into max.co.il/login

Step 2: Starting to scrape max

![image](https://user-images.githubusercontent.com/2265043/107610406-348d7e80-6c4a-11eb-9625-13676074b0f3.png)

If I will switch manually to the correct tab I can enter (manually) the username/password and it works, but  the automatic process isnt working. its hang on this page.

**Comment by esakal** [comment]
@MosheL Hi
Something is off in your version, are you using the latest one? see the code [here](https://github.com/eshaham/israeli-bank-scrapers/blob/2f9693baa3356002aabf22bb5086c3a00e3bbd80/src/scrapers/max.ts#L241) - it will always open the mentioned view and then simulate a click on the כניסה עם סיסמא tab.

I ran it now twice and it worked as expected

**Comment by esakal** [comment]
@MosheL hi just checking if you still experience it

**Comment by MosheL** [comment]
Hi 

thanks
I was tried again, in a new project.

first test - password expired.
so I was changed the password and tried again.

the chromium opened, the browser navigated to max website but the process was hangs after successful login.

scraping failed for the following reason: GENERIC
![image](https://user-images.githubusercontent.com/2265043/108621500-9d8ba800-743b-11eb-9edc-10921c793ef9.png)

**Comment by MosheL** [comment]
I tried again, and it hangs before the login stage. and again, and it work (the first step - the login).

I can't change your code now as I am using the code from NPM.   need  I  use the project from github and try to debug it ?

**Comment by esakal** [comment]
@MosheL try the next version first. `npm install israeli-bank-scrapers@next`. let me know if it worked for you

**Comment by tpseven-777** [comment]
@esakal I've just tried to download the next version, and getting this:
waiting for redirect from https://www.max.co.il/homepage/welcome
scraping max failed for the following reason: TIMEOUT

**Comment by MosheL** [comment]
the login stage is working. after the login it does nothing.

**Comment by tpseven-777** [comment]
@MosheL Working for you, but doesn't work for me in both current and next versions.
I'm not sure which version you've got

**Comment by tpseven-777** [comment]
Ok The issue for me (with @next) version was that the password had expired/changed/was wrong, 
Note that the fail reason is TIMEOUT, so I've missed it.
Correct PW works with @next version.

**Comment by esakal** [comment]
@tpseven-777  thats great! 
regrading the password expired this is a known problem, it take times for people to get it and once it happens people tend to replace password and not try to update the library.

anyhow @eshaham when can you deploy an official version?

**Comment by esakal** [comment]
@MosheL I'm not sure how I can assist. because it works on my machine (I run the script few times a week) and also @tpseven-777  managed to make it works with next version. you can record your view and send it to me (either in private or here) if you want - I might be able to notice a broken flow or something similar

**Comment by MosheL** [comment]
@esakal   Tested again for one month. it works. maybe hangs for large date range.

thanks !

**Comment by eshaham** [comment]
@esakal released

**Comment by esakal** [comment]
@eshaham can you please verify the release you did 11 days ago 1.0.2, someone reported that it is broken and I think he is right.

I'm keeping this issue for now until we will be able to get verification

**Comment by eshaham** [comment]
@esakal released 1.0.3

**Comment by baruchiro** [comment]
I think the MAX scraper is OK and you can close this issue
