### ISSUE TITLE
Bank Otsar Hahayal is broken - table#dataTable077" failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by hcosteff** [eshaham/israeli-bank-scrapers#555]
scraping Bank Otsar Hahayal
Bank Otsar Hahayal: START_SCRAPING
Bank Otsar Hahayal: INITIALIZING
Bank Otsar Hahayal: LOGGING_IN
Bank Otsar Hahayal: LOGIN_SUCCESS

Bank Otsar Hahayal: TERMINATING
Bank Otsar Hahayal: END_SCRAPING
success: false
error type: GENERIC
error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
Error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-task.js:90:33)
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scraping-main-menu.js:10:5)
(node:179) UnhandledPromiseRejectionWarning: Error: waiting for selector "table#dataTable077" failed: timeout 30000ms exceeded
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-base.js:61:11)
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scrape-task.js:90:33)
    at exports.default (/home/budgeter/israeli-ynab-updater/src/scrape/scraping-main-menu.js:10:5)
(node:179) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:179) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by esakal** [comment]
@hcosteff I now see that you have two different issues for Bank Otsar, are they related?
Maybe Bank Otsar changed their site. 
If it wasn't yet resolved you will need to download the repo and find the issue using the debugger, unless someone else with Bank Otsar account can do it

**Comment by ivorco** [comment]
> @hcosteff I now see that you have two different issues for Bank Otsar, are they related?
> Maybe Bank Otsar changed their site.
> If it wasn't yet resolved you will need to download the repo and find the issue using the debugger, unless someone else with Bank Otsar account can do it

I have bank Otsar Hahayal but will have to see how I can debug it.
If you want the HTML file I can share it without my details if that helps.

**Comment by NoamGit** [comment]
I have the same problem. Solved by adding 
```
      if (hasNextPage) {
        await clickButton(page, '#Npage');
        await waitForNavigation(page);
        const dataTable = await page.$('#dataTable077');
        if (dataTable != null) {
               await waitUntilElementFound(page, 'table#dataTable077');
}
      }
```
In the scraper file. I can pull a PR if needed
