### ISSUE TITLE
1.0.2 is broken

### ISSUE THREAD

**Issue by noamokman** [eshaham/israeli-bank-scrapers#556]
Hey,
Version 1.0.2 is published without any files.
Just the readme and package.json.

**Comment by esakal** [comment]
@eshaham I was able to confirm that 1.0.2 is broken, although when I pull master and build it the library seems fine, so I believe it happens due to local issue during deployment.

I ran
```
npm ci
npm run prepare:default
npm pack
```
and observed the file being created.

Can you please release a new version and confirm its content?

**Comment by esakal** [comment]
@noamokman thanks for reporting, for now feel free to use `israeli-bank-scrapers@next`, it is created automatically from master branch and I confirmed that it includes the missing `lib` folder from the official version.

**Comment by noamokman** [comment]
Yeah, thanks!
I'm just using 1.0.1 in the meanwhile :)

**Comment by eshaham** [comment]
Deployed 1.0.3 which seems to be working 👌
