### ISSUE TITLE
Bank Otsar many "empty" transactions

### ISSUE THREAD

**Issue by hcosteff** [eshaham/israeli-bank-scrapers#557]
This is output from scraping bank otsar
`<U+FEFF>"Date","Payee","Inflow","Status","Installment","Total"
"02/02/2020","",0,"completed",,
"02/02/2020","",0,"completed",,
"07/02/2020","",0,"completed",,
"07/02/2020","",0,"completed",,
"09/02/2020","",0,"completed",,
"10/02/2020","",0,"completed",,
"10/02/2020","",0,"completed",,
"11/02/2020","",0,"completed",,
"11/02/2020","",0,"completed",,
"19/02/2020","",0,"completed",,
"19/02/2020","",0,"completed",,
"21/02/2020","",0,"completed",,
"23/02/2020","",0,"completed",,
"01/03/2020","",0,"completed",,
"01/03/2020","",0,"completed",,
"02/03/2020","",0,"completed",,
"02/03/2020","",0,"completed",,
"07/03/2020","",0,"completed",,
"07/03/2020","",0,"completed",,
/budgeter/download/tasks/maintask/09-03-2021_19-41-15/Bank\ Otsar\ Hahayal\ \(14-348-161182\).csv (END)`

Notice that the dates are all 1 year back, and they are all 0 with no payee, etc.

Seems like a basic bug in the scraper?

**Comment by esakal** [comment]
@hcosteff hello, I'm sorry but I don't have account in Bank Otsar so I cannot help here. maybe @matanelgabsi can help
