### ISSUE TITLE
Specific transaction cannot be read from Cal

### ISSUE THREAD

**Issue by tpseven-777** [eshaham/israeli-bank-scrapers#558]
Max scraper fails to parse:
getting 'unknown transaction type 68'
for this txn:
![image](https://user-images.githubusercontent.com/74489861/110911761-c35deb80-831b-11eb-956b-c07c86ce34c6.png)

**Comment by esakal** [comment]
@tpseven-777 the scraper behave as expected, it doesn't recognise transaction type 68 so it abort the process. I created a PR to support it but I need you to test it before I can merge it (I don't have such a transaction type in my account).

It is a bit weird for me as all the other types of Max seems to be textual and you show here numeric type. But let's see how it works for you

**Comment by esakal** [comment]
@tpseven-777 can you confirm the PR?

**Comment by tpseven-777** [comment]
Sure @esakal ,but I'm not experienced with JS. I'll be able to pull the PR branch, but not sure I know what to do with it afterwards.

**Comment by tpseven-777** [comment]
So @esakal, how can we progress from here? Any chance you could prepare a test version?

**Comment by tpseven-777** [comment]
@esakal I'm not sure if this was effective for Visa too, but I'm now getting the same error:
unknown transaction type 68
For scraping visa cal.
Tested with current and next version, and also for some dates which were successful in the past (hence probably something had changed in visa cal's website that broke the scraper)

**Comment by esakal** [comment]
@tpseven-777 hi, sorry I thought it was clear that we have tests already in the codebase. You have two ways to test it:

*Option 1*
Where are you depending on this library? if you are using NPM to depend on this library you can just install temporary from GitHub branch directly using this command `npm i eshaham/israeli-bank-scrapers#max-67`

*Option 2*
If you want to use the built-int tests you need to clone this repo and run them using [this guide](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#testing-the-scrapers)

Let me know how it worked for you

**Comment by tpseven-777** [comment]
Hi @esakal 
I've updated to the latest version, and went through all of my cards.
The only card I'm unable to scrape is **VISA CAL** (and not MAX as I've mistakenly applied to earlier)
Here's how it looks like on their web site. This transaction is there for every single month from now on..
![image](https://user-images.githubusercontent.com/74489861/116817444-06e01380-ab6f-11eb-9173-3c6e667aa90e.png)

Could you please patch on cal scraper and hand me a test version?
Thanks!

**Comment by esakal** [comment]
@tpseven-777 Hi! unfortunately I cannot do that, in the codebase we handle transaction type which is numeric and I cannot determine the type of the transaction you have based on the UI snapshot.

Do you know how to enable dev tools and monitor the network? If so, filter requests by `CalTransactions`, you should find a request like that per each card, then check the response of the relevant card and send here the value of the field `TransType`

**Comment by esakal** [comment]
@tpseven-777 feel free to check. 
@eshaham fyi

**Comment by tpseven-777** [comment]
I've tried this, following your previous guidance, but that didn't work:
`[ec2-user@ip-1-1-1-1 ~]$ npm i eshaham/israeli-bank-scrapers#visa-68
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eshaham/israeli-bank-scrapers.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2021-05-02T19_52_43_751Z-debug.log`

**Comment by esakal** [comment]
@tpseven-777 I don't remember why I said you can do it like that, it shouldn't let you pull the change like that.

how would you normally test things like that? do you have knowledge in node.js? if so you probably know how to test it, if not let me know and I will think how to proceed.

**Comment by tpseven-777** [comment]
@esakal I can't say that I have a standard testing procedure for this project, only for the code which uses this project.
I got the impression that making this change locally and then transpiling it (is this the correct word? I'm really not sure), should let me test it. But I'm not sure how this process should be triggered. 
I'll be glad to learn though :)

**Comment by tpseven-777** [comment]
@esakal I've tested this code by applying the relevant part to visa-cal.js and running.
Works well, 
Thanks!
