### ISSUE TITLE
Visa Cal: unknown transaction type 1

### ISSUE THREAD

**Issue by etaytch** [eshaham/israeli-bank-scrapers#562]
Hey All,
I'm getting an `unknown transaction type 1` for Visa Cal scraper:

```
Visa Cal: START_SCRAPING
Visa Cal: INITIALIZING
Visa Cal: LOGGING_IN
Visa Cal: LOGIN_SUCCESS
Visa Cal: TERMINATING
Visa Cal: END_SCRAPING
success: false
error type: GENERIC
error: unknown transaction type 1
```

**Comment by esakal** [comment]
hi,
In order to support this kind of transaction please provide information about it, you can copy the description in Hebrew from there website

**Comment by esakal** [comment]
@etaytch I add support for that type as part of another PR. as you didn't provide description of that transaction I assumed this is like any other transactions and not instalments transaction

**Comment by etaytch** [comment]
Thanks @esakal and sorry for responding so late.
I currently don't have access to the Visa Cal account.
I'll update once I do 🙏

**Comment by esakal** [comment]
@etaytch no worries, once you will provide the description of that type we will be able to support it
