### ISSUE TITLE
Request: Create a very simple CLI

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#569]
I see a very simple code [here](https://github.com/eshaham/israeli-bank-scrapers#getting-started) that required just a config of `credentials` and `options`. Someone asked me how to use this project inside a C# project, and I suggested to him to run it as a process. But he can't because this project is not an executable one.

What I suggest is to create a very simple executable file (by the [package.json bin feature](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin)) that will get JSON file with the config (or stdin) and will print the results.

You know, a simple script, and keep the security ownership in the user.

**Comment by esakal** [comment]
@eshaham wdyt?

**Comment by tpseven-777** [comment]
@baruchiro Well, for me this was we an opportunity to learn some Node.JS 
That someone who asked you probably doesn't want the data just to be printed on the screen, but rather do something with it.
Doing that something should probably be done under node.JS
