### ISSUE TITLE
Status property

### ISSUE THREAD

**Issue by asfktz** [eshaham/israeli-bank-scrapers#57]
Sometimes, recent transactions may change.

For example, in Bank Hapoalim, transactions above the fold are still `"pending"`:
![screen shot 2018-01-25 at 9 30 46 pm](https://user-images.githubusercontent.com/199747/35408496-ffbbd098-0217-11e8-9a99-217d635caf47.jpg)

Having a `status` field will be useful to differentiate between `pending` and `posted` transactions

Example for `Bank Hapoalim`:

```js
status: txn.serialNumber === 0 ? 'pending' : 'posted'
````

**Comment by eshaham** [comment]
@asfktz I've created [a new branch](https://github.com/eshaham/israeli-bank-scrapers/tree/txn_status) for this feature.
Feel free to create a PR against this branch for Bank Hapoalim.
I will try to push code for Discount bank within the next week or so.
I don't think this concept exists in credit cards, does it?

**Comment by asfktz** [comment]
> Feel free to create a PR against this branch for Bank Hapoalim.
Nice! I will

> I don't think this concept exists in credit cards, does it?
Hmm.. I don't think so too
