### ISSUE TITLE
Otsar hayal scraper is broken

### ISSUE THREAD

**Issue by baaraak** [eshaham/israeli-bank-scrapers#583]
The scraper returns duplicates transaction and missing fields in some cases.
I know that 'otsar hayal' changed their website couple of months ago...

I'm using this in my own app and manage to fix it in my fork
it's seems that the problem is here: `parseTransactionPage`
https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/otsar-hahayal.ts#L97

I changed it to this and it seems to work great
```
async function parseTransactionPage(page: Page) {
  const tdsValues = await pageEvalAll(page, '#dataTable077 tbody tr', [], (trs) => {
    return trs.map((el) => ({
      date: el.querySelector('.date').innerText,
      description: el.querySelector('.reference').innerText,
      credit: el.querySelector('.credit').innerText,
      debit: el.querySelector('.debit').innerText,
      balance: el.querySelector('.balance').innerText,
    }));
  });

  // first row is total balance info, not a transaction
  return tdsValues.splice(1);
}
```

**Comment by esakal** [comment]
Hi @baaraak thanks for your insights. If you can create a PR from your fork I will be able to merge it. I prefer not doing it by myself because I will not be able to test my changes.

Thanks!

**Comment by baaraak** [comment]
Done
