### ISSUE TITLE
Request: add support for Bank Yahav

### ISSUE THREAD

**Issue by hannanel100** [eshaham/israeli-bank-scrapers#589]
I recently moved to Bank Yahav and was wondering if adding support for the bank is possible or planned at all.

**Comment by esakal** [comment]
Hello @hannanel100, we always welcome contributors adding finance instituted that they have access to  like you with Bank Yahav. You can start from the [contributing.md](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md) file to learn more how to accomplish it. 

Adding new institutes is possible only for those who have access to them, unfortunately neither @eshaham nor me have such an account there so it is not planned from our side, but again feel welcome to contribute and add that support :)

**Comment by hannanel100** [comment]
Do you think this can be done by a first time contributor? I would love to give it a go, it would be great to have someone to direct questions to....

**Comment by baruchiro** [comment]
I think it is the best way to be a first-time contributor- I did the same way...
Just look at other banks that already implemented and get ideas.

I think you can ask questions here, I'm a contributor and I'm here to help :-)

**Comment by baruchiro** [comment]
BTW, you know [Riseup](https://www.riseup.co.il/)?
It is interesting that they don't have Bank Yahav support, like this project...

**Comment by hannanel100** [comment]
__😜____

**Comment by gczobel** [comment]
@hannanel100
I started working on that, but I have zero UI expertise and don't have the time to continue.
I actually have a fork and it's working for me.
You can take a look here: https://github.com/gczobel/israeli-bank-scrapers/blob/yahav/src/scrapers/yahav.ts

**Comment by hannanel100** [comment]
Where exactly did you get stuck?

**Comment by gczobel** [comment]
Check the `searchByDates` function. I never figured out how to select the dates correctly.
Actually is hardcoded to choose the last 3 months from the drop down.

But everything else is working. I use that fork daily on a cron.

**Comment by esakal** [comment]
@gczobel can you add snapshots of the dropdown and the date selectors?
usually what happens is that you need to pick the custom dates option in the drop menu and then to type the dates into the components. if they are using a date selector and block manual typing you sometimes can still set the value and it will catch up. 

did you try that?

**Comment by gczobel** [comment]
@esakal
Yes, check here: https://github.com/eshaham/israeli-bank-scrapers/issues/542

**Comment by esakal** [comment]
@gczobel this one looks promising 
https://stackoverflow.com/questions/58507589/how-to-use-this-datepicker-with-puppeteer
remove the readonly from the field and type, it sounds reasonable, can you try?

**Comment by gczobel** [comment]
@esakal I know it's old but I was not able to check this until now.
I tried the workaround you suggested and it's not working. 
I'm able to remove the 'readonly' and put the new text in the correct format. But nothing happens.
I tried doing  `await page.keyboard.press('Enter') ` to check if this fire something but no...

Every click open the  'calendar' that you can see in the pictures in #542
