### ISSUE TITLE
GENERIC: Error: failed to find element matching selector ".main_balance" when scraping beileumi

### ISSUE THREAD

**Issue by sushi30** [eshaham/israeli-bank-scrapers#610]
When using the beinleumi scraper:

```
GENERIC: Error: failed to find element matching selector ".main_balance"
```

Checking with UI it appears the main balance indeed goes missing after the first page.

## Frist page
![image](https://user-images.githubusercontent.com/26347589/136078330-ec982d4a-164d-4816-8652-a32245d75742.png)

## Second page
![image](https://user-images.githubusercontent.com/26347589/136078112-ae00b032-201d-484b-8b95-6f333552c604.png)

**Comment by esakal** [comment]
@sushi30 please see PR #611
