### ISSUE TITLE
LeumiCard scraper fails on v0.5.2

### ISSUE THREAD

**Issue by asfktz** [eshaham/israeli-bank-scrapers#62]
The LeumiCard scarper fails with version `0.5.2` of `israeli-bank-scrapers`

It throws `TypeError: Cannot read property 'timeout' of undefined` when trying to log in.

I dag into the code and found that the error is originally thrown by `waitUntil`, but swallowed by its `catch` block on line 25:
https://github.com/eshaham/israeli-bank-scrapers/blob/cd8ba284dc0de053278b5d032591d1f8487af584/src/helpers/waiting.js#L17-L27

The original error message is: `Cannot find context with specified id undefined`
Which seems related to https://github.com/GoogleChrome/puppeteer/issues/1325

My first attempt was to downgrade puppeteer back to `0.13.0` but it does not solve the problem.
Using version `0.5.1` of  `israeli-bank-scrapers` did, so it has to be some other recent change.
Here's the diff between the two versions, could be related to the transition from "id" to "selector"?

Here's the full diff: https://github.com/eshaham/israeli-bank-scrapers/compare/v0.5.1...master

I made a simple test case to demonstrate the bug:

```js
const { createScraper } = require('israeli-bank-scrapers');

async function run () {
  const scraperName = 'leumiCard';

  const scraper = createScraper({
    companyId: 'leumiCard',
    verbose: true
  });

  const credentials = {
    username: '<user name>',
    password: '<user password>'
  };

  scraper.onProgress((companyId, payload) => {
    console.log(`${companyId}: ${payload.type}`);
  });

  let scapeResults;
  try {
    scapeResults = await scraper.scrape(credentials);
  } catch (e) {
    // fails with TypeError: Cannot read property 'timeout' of undefined
    console.error(e);
    return;
  }

  console.log(scapeResults)
}

run();
```

**Comment by eshaham** [comment]
@asfktz thanks for reporting, I'll take a look
