### ISSUE TITLE
GENERIC: MAX scrapper fails with error "Evaluation failed: TypeError: Failed to fetch"

### ISSUE THREAD

**Issue by DimDimi4** [eshaham/israeli-bank-scrapers#625]
As described in the title MAX scrapper fails constantly with this error for couple of days now. There is no debug messages in scrapper itself so I dont know where exactly does it happens.

**Comment by erikash** [comment]
+1 here

**Comment by ifeins** [comment]
I'm getting this as well

**Comment by NetanelBrauner** [comment]
Same issue for me

**Comment by tpseven-777** [comment]
+1

**Comment by erikash** [comment]
Hi guys,
I've opened a PR with a fix for this issue.. would appreciate if you can test it..
@esakal FYI
https://github.com/eshaham/israeli-bank-scrapers/pull/629

**Comment by esakal** [comment]
@DimDimi4 please check with the version just deployed

**Comment by gczobel** [comment]
Works in my private branch using the proposed fix.

**Comment by DimDimi4** [comment]
> @DimDimi4 please check with the version just deployed

It does work now! Thanks.
