### ISSUE TITLE
Collaboration on scrapers

### ISSUE THREAD

**Issue by Urigo** [eshaham/israeli-bank-scrapers#630]
Hi, 
About 2 years ago I suggested a couple of changes into how the scrapers are build and wanted to contribute.

Some of these changes were accepted (migration to TS, but at the end I wasn't the one who did the actual work...) and some rejected.
The main ones who got rejected were around getting the raw and full response from the scrapers (Related to this one as well: https://github.com/eshaham/israeli-bank-scrapers/issues/418), providing schemas for the results and dependency management.

What I ended up doing is creating this library instead, which I've been using for a couple of apps and business for the past 2 years: https://github.com/Urigo/israeli-bank-scrapers-modern-schemas

It brings in the raw response from the original scrapers, it validates these responses against json-schemas (so I would know when things are changing) and generates Typescript types from these json-schemas.

I actively update and use this library on a daily basis for 2 years now.
I think it can be a good idea to collaborate.
One option that I think of is to replace the current implementation of Hapoalim and Isracard to use my library as a dependency.
Because I've placed the validation behind an optional flag, in this library I could remove these checks which I understand you don't want and also once you get the full response I still use your code that normalize the response to the shared structure (but this time it would be fully typed code thanks to the auto-generated types from my library).

Would love to hear your thoughts and feedback about this direction

Thanks for creating such an important library!!

**Comment by baruchiro** [comment]
I have a question.

What is the **full response** you're talking about? I guess you're talking about SPA scrapers that catch the server response for data, but in the scrapers I worked on, it was done by parsing an HTML table. What is the **raw data** there?

Another suggestion, I don't know if you implemented it like that, is to integrate the schema validation in the tests. It will not help in production, because you can't solve the problem without getting into the source code.

Good luck!

**Comment by Urigo** [comment]
@baruchiro yes, by full response I meant the server response data (Poalim and Isracard), but in general and with the context of an HTML scraper I think it means every piece of data you can get out from the website (HTML and network or any other way you can get as much data as possible).
So that we have all the data that is possible to extract and might be useful to someone, and in a later stage filter from that the shared data between different scrapers.

I haven't written tests yet for the scraper (I'm not sure I will after 2 years...) so I didn't full understand your second question.
I imagine these schemas could be very useful for testing, to test the origin source and if it sends the expected result

**Comment by esakal** [comment]
Hi @Urigo I just wanted to let you know that I saw your suggestion and I'll try to address it soon. I need to finalize some other thing first. 

Thanks and enjoy the weekend

**Comment by Urigo** [comment]
Hi @esakal , we can work on it together, don't address it by yourself, I wrote a whole library and I can help you integrate it
