### ISSUE TITLE
waitFor is deprecated

### ISSUE THREAD

**Issue by tpseven-777** [eshaham/israeli-bank-scrapers#634]
Getting this when scraping amex:
`waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.`
Latest version

**Comment by esakal** [comment]
Thanks, we will address it when we will upgrade the puppeteer dependency. At the moment this is only a warning and shouldn't impact the functionality of the scrapers
