### ISSUE TITLE
Otsar Hahayal bank transactions date is being written as last year instead of current year

### ISSUE THREAD

**Issue by ReaBar** [eshaham/israeli-bank-scrapers#637]
I'm not sure if its an issue in israeli bank  scrapers but I'm using caspion to scrape my financial data and the dates for bank otsar hahayal are last year instead of this year. can anyone verify it?

**Comment by esakal** [comment]
@ReaBar I don't have otsar hahyal. But a question. is the date of the transactions in the following format? dd/yy/mm?

https://github.com/eshaham/israeli-bank-scrapers/blob/3fcfb7a5cd619a33a7022cc2708a45c084c7f529/src/scrapers/otsar-hahayal.ts#L17

**Comment by ReaBar** [comment]
> @ReaBar I don't have otsar hahyal. But a question. is the date of the transactions is shown as four letters or two letters?
> 
> https://github.com/eshaham/israeli-bank-scrapers/blob/3fcfb7a5cd619a33a7022cc2708a45c084c7f529/src/scrapers/otsar-hahayal.ts#L17

Hi @esakal,
example from the excel file:
`<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/reaba/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/reaba/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



date | description
-- | --
  |  
2020-01-02T22:00:00.000Z | (הפקדת שיק בסלולר (1 שיק



</body>

</html>
`

**Comment by esakal** [comment]
yes, i meant in the website, can you share the day of the same transaction in the browser?

**Comment by ReaBar** [comment]
sure.
this is the formatting in the bank's website: 20/10/2021

**Comment by esakal** [comment]
@ReaBar actually the date format is wrong. In the date you showed me it has 4 digits in the year so it should have been YYYY instead of YY

I can help you with that even that I don't have an account there. 

To do that I'll need you to reply with dates examples  from Jan-September, from the beginning of the month days 1 to 9.

I need to know if they use 0 for days/month with single digit. Some examples:
01/07/2021
1/07/2021
1/7/2021
01/7/2021

I believe it will be either 01/07/2021 or 1/7/2021 but I have seen inconsist formats in the past and I don't want to guess.

Thanks

**Comment by ReaBar** [comment]
@esakal the format is: 01/01/2021 (trailing zeros)

**Comment by ReaBar** [comment]
@esakal the format is: 01/01/2021 (trailing zeros)

**Comment by esakal** [comment]
@ReaBar please run the tests of otsar hahayal against my PR, let me know if it fixed it.

**Comment by ReaBar** [comment]
@esakal I would be glad to run those tests but I have no experience with typescript and I'm consuming this project through caspion and not directly from this repository.

**Comment by ReaBar** [comment]
> @esakal I would be glad to run those tests but I have no experience with typescript and I'm consuming this project through caspion and not directly from this repository. is there a way to run this directly and save output to gsheet or excel?

@esakal what do you say? how can I run the app and save the output? I would be glad to test it out

**Comment by esakal** [comment]
@ReaBar please track releases of Caspion and let us know once it uses the fix if it has worked or caused a regression (less likely)

@brafdlog fyi

**Comment by brafdlog** [comment]
@ReaBar See https://github.com/brafdlog/caspion/pull/306

**Comment by ReaBar** [comment]
@brafdlog thanks, waiting for the release and I will check

**Comment by brafdlog** [comment]
@ReaBar try https://github.com/brafdlog/caspion/releases/tag/v0.0.12-beta

We didn't use discord, but I am considering our options for communication. So opened one and we can try it out.
You can join here: https://discord.gg/ejfZrfrN

**Comment by ReaBar** [comment]
@brafdlog it works.
I'll connect to discord as well.

**Comment by esakal** [comment]
@ReaBar great news! enjoy. 

@brafdlog having discord to caspion sounds like a great idea
