### ISSUE TITLE
Mizrahi future transactions is breaking in case of error

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#639]
1. The future transactions in Mizrahi is not working in this case:
![image](https://user-images.githubusercontent.com/17686879/145565123-c5cbcc3d-e615-43cd-af0e-c05ed4387e76.png)
1. I think if the future transactions is not working, it shouldn't fail the whole scrape.

**Comment by esakal** [comment]
Hi @baruchiro, the API fails when we are not sure it fetched all the data as expected. If we will silently ignore scraping errors, even for future transactions, the outcome will be that users will assume there aren't any as the scrapping will pass.

Do you have a way to fix it?

**Comment by baruchiro** [comment]
Sorry, I can't find the time to fix this
