### ISSUE TITLE
Consider returning a serialized response

### ISSUE THREAD

**Issue by asfktz** [eshaham/israeli-bank-scrapers#64]
Hi @eshaham!

When working with israeli-bank-scraper, I prefer to save the results to a JSON file and work with it instead, to avoid being risked in getting my IP blocked the Bank.

Since the scraper returns a Date object in the results, It defers from the serialized cached response and requires an extra step to convert the dates back when deserializing.

I would like to suggest that instead of Date Object, the response will return with Date strings (ISO format)

![screen shot 2018-02-03 at 9 33 03 pm](https://user-images.githubusercontent.com/199747/35770754-da02dacc-0929-11e8-9412-041038e07a2d.png)

![screen shot 2018-02-03 at 9 34 47 pm](https://user-images.githubusercontent.com/199747/35770766-285d0ecc-092a-11e8-9df2-961b954caae5.png)

What do you think?

I can send a PR if you're interested

**Comment by eshaham** [comment]
@asfktz sounds like a good idea, PR welcome!
