### ISSUE TITLE
Error while fetching page by Max scraper

### ISSUE THREAD

**Issue by nmazuz** [eshaham/israeli-bank-scrapers#645]
Max scraper has an issue in last few weeks

During the scraper execution I am getting the following error:
`
-f | {
0|israel-f |   success: false,
0|israel-f |   errorType: 'GENERIC',
0|israel-f |   errorMessage: 'Evaluation failed: SyntaxError: Unexpected end of JSON input\n' +
0|israel-f |     '    at __puppeteer_evaluation_script__:11:26\n' +
0|israel-f |     '    at l.invoke (https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:6867)\n' +
0|israel-f |     '    at t.run (https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:2266)\n' +
0|israel-f |     '    at https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:17042\n' +
0|israel-f |     '    at l.invokeTask (https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:7485)\n' +
0|israel-f |     '    at t.runTask (https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:2881)\n' +
0|israel-f |     '    at m (https://www.max.co.il/polyfills-es2015.757f654fe686905e8c38.js:1:9479)'
0|israel-f | }
`
Something with this JS file cant be phrased (polyfills-es2015.757f654fe686905e8c38.js)
I tried to ignore js files during the fetch by using page.setJavaScriptEnabled(false) but it didnt help.

Is anyone is experience the same issue? Is someone can help to solve it please.

Thanks

**Comment by esakal** [comment]
Hi @nmazuz I'm using max scraper daily so it might indicate on something not related to the scraper logic.
Did you make sure you are using the latest version? Which version of israeli-bank-scrapers or israeli-bank-scrapers-core are u using? 

It looks like the error is when trying to run something in the polyfills of max.co.il but it doesn't make sense as we are using puppeteer which is usually updated and doesn't require many polyfills. And if it does it requires the same ones to all.

Please respond with the version you are using and we will think what can be done. You can also verify that your credentials work by running the tests of the project, just follow [this guide](https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md#testing-the-scrapers)

**Comment by nmazuz** [comment]
Upgrading version solved the issue.
Thanks!
