### ISSUE TITLE
Mercantile bank

### ISSUE THREAD

**Issue by naji-makhoul** [eshaham/israeli-bank-scrapers#650]
Is there support for Mercantile Bank?

**Comment by Mitrij** [comment]
Yes, the same as discount. The only difference to make it work I had to change login url:
loginUrl: `${BASE_URL}/login/?multilang=he&bank=m&t=p`,
This worked for me.

**Comment by esakal** [comment]
@Mitrij is this the only difference? the login url?

**Comment by Mitrij** [comment]
Yes, it is the same system. But looks like, it needs this parameters for "Mercantile bank".

**Comment by esakal** [comment]
@Mitrij if you'll provide a PR we will be able to add it to the library :)

**Comment by Mitrij** [comment]
I'm sorry, what is PR?

**Comment by esakal** [comment]
PR stands for "pull request" with the changes needed so we will be able to merge it into the deployed version

**Comment by esakal** [comment]
@Mitrij please reopen the issue with update once relevant. Thanks
