### ISSUE TITLE
Is there a way to get the future bill for credit cards such as Cal?

### ISSUE THREAD

**Issue by LiranBri** [eshaham/israeli-bank-scrapers#655]
Is there a way to get the future bill (debt) for credit cards such as Cal? or only transactions are currently supported?

**Comment by LiranBri** [comment]
I see in code now that there isn't. I can contribute a PR but how would you like me to structure it in the response object? as there are no matching fields currently for it.

probably we need new fields such as:
```js
futureDebits: [
   { bankAccount: "612-12345", amount: 143, when: "2020-03-01" },
   { bankAccount: "612-12345", amount: 143, when: "2020-03-01" },
]
```

**Comment by esakal** [comment]
I have merged the PR but the magic link was incorrect so I'll close this one manually
