### ISSUE TITLE
Support foreign currencies

### ISSUE THREAD

**Issue by thedrow** [eshaham/israeli-bank-scrapers#663]
I've looked into two scrappers, one for Mizrahi and one for Beinleumi and both of them seem to support scrapping accounts in Shekels only.
Is there a plan to add support for foreign currencies?

**Comment by esakal** [comment]
Hello, 
i believe they were added by users without foreign currencies. If you have such an account and you can contribute to them that would be awesome.

**Comment by naorpeled** [comment]
@esakal I would love to assist with the Mizrahi scraper, feel free to assign me if you'd like.
Regarding Benleumi, I don't have any accounts there.
