### ISSUE TITLE
Mizrahi scrapper is no longer working after site changes

### ISSUE THREAD

**Issue by Asafb26** [eshaham/israeli-bank-scrapers#668]
It seems like Mizrahi has a new site (not sure if it's a rollout or 100% live, can you confirm?)
now Mizrahi scrapper is no longer working due to selectors/URL changes and probably some CSR changes
<img width="1311" alt="Screen Shot 2022-03-23 at 2 26 59" src="https://user-images.githubusercontent.com/6785580/159598494-fb372122-ff08-4fc9-9175-97a39dd91ca0.png">

**Comment by esakal** [comment]
should be resolved as part of #673
