### ISSUE TITLE
Isracard scraper login fail

### ISSUE THREAD

**Issue by esm7** [eshaham/israeli-bank-scrapers#674]
Hey,

For some reason the Isracard scraper stopped being able to login. I believe (though not 100% sure) that they changed the format of how the page transitions between password-based login and SMS-based login (https://digital.isracard.co.il/personalarea/Login/).

```
scraping Isracard
Isracard: START_SCRAPING
Isracard: INITIALIZING
Isracard: LOGGING_IN
Isracard: LOGIN_FAILED
Isracard: TERMINATING
Isracard: END_SCRAPING
success: false
error type: INVALID_PASSWORD
error: undefined
```

**Comment by esm7** [comment]
My bad, closing!

**Comment by dorbenzvi** [comment]
@esm7 What was the issue?
I'm facing the same thing now.

**Comment by esm7** [comment]
It was a straight-forward error on my end, I haven't realized that my password changed a few weeks earlier, I haven't used israeli-bank-scapers in those last weeks, so I forgot to update the config with the new password :shrug:
