### ISSUE TITLE
futureDebit object is undefined - Hapoalim Scraper

### ISSUE THREAD

**Issue by samsonmoshe** [eshaham/israeli-bank-scrapers#675]
After running the scraper, I get the transactions, but not the future debits.

I thought this should contain the future credit card information... Have I misunderstood this?

**Comment by esakal** [comment]
It depends on the scraper. I don't have Hapoalim account anymore so I cannot say for sure. Based on the codebase it looks like we scrape in hapoalim using specific api by providing current date as end date. This is a common practice in this library. Some of the institutes returns future transactions but based on your issue it might not be the case for Hapoalim. I don't see any filtering logic there that remove future transactions or something similiar

**Comment by esakal** [comment]
@samsonmoshe feel free to re-open if relevant
