### ISSUE TITLE
scraping failed for the following reason: Protocol error (Performance.enable): Target closed.

### ISSUE THREAD

**Issue by davidd22** [eshaham/israeli-bank-scrapers#693]
getting this ^ error after npm install the package and trying to run this code...

my **main.ts** file

`
(async function () {
  try {
    // read documentation below for available options
    const options = {
      companyId: CompanyTypes.leumi,
      startDate: new Date('2020-05-01'),
      combineInstallments: false,
      showBrowser: true,
    };

    // read documentation below for information about credentials
    const credentials = {
      username: 'vr29485',
      password: 'sometingsomething',
    };

    const scraper = createScraper(options);
    const scrapeResult = await scraper.scrape(credentials);

    if (scrapeResult.success) {
      scrapeResult.accounts.forEach((account) => {
        console.log(
          `found ${account.txns.length} transactions for account number ${account.accountNumber}`,
        );
      });
    } else {
      throw new Error(scrapeResult.errorType);
    }
  } catch (e) {
    console.error(`scraping failed for the following reason: ${e.message}`);
  }
})();

`

**Comment by esakal** [comment]
Sorry @davidd22  I don't encounter this issue on my end. Anyone else experience the same issue?

In the meanwhile try to debug it with logs using `DEBUG=israeli-bank-scrapers:*` and use it to diagnose the step that throw this error.

**Comment by esakal** [comment]
@davidd22 please re-open the issue with update if it is still relevant.
