### ISSUE TITLE
Beinleumi login is broken

### ISSUE THREAD

**Issue by konfortes** [eshaham/israeli-bank-scrapers#697]
Hey @eshaham, maintainers, love this repo ❤️ 

It seems like the beinleumi login is broken, I'm not really sure why, the code appears to be okay.
I was, however, able to reproduce it in a simplified snippet (below) and fix it by adding an ugly `waitForTimeout(1000)` 

```typescript
import * as dotenv from 'dotenv'
dotenv.config({ path: '../.env' })

import * as puppeteer from 'puppeteer'

const BASE_URL = 'https://online.fibi.co.il'
const LOGIN_URL = `${BASE_URL}/MatafLoginService/MatafLoginServlet?bankId=FIBIPORTAL&site=Private&KODSAFA=HE`
const TRANSACTIONS_URL = `${BASE_URL}/wps/myportal/FibiMenu/Online/OnAccountMngment/OnBalanceTrans/PrivateAccountFlow`

;(async () => {
    const browser = await puppeteer.launch({ headless: false })
    try {
        const page = await browser.newPage()
        await page.goto(LOGIN_URL)
        await page.waitForSelector('#continueBtn')

        await page.type('#username', process.env.BANK_USERNAME || '')
        await page.type('#password', process.env.BANK_PASSWORD || '')

        await page.waitForTimeout(1000)
        await page.click('#continueBtn')
    } catch (ex) {
        console.log(ex)
    } finally {
        await browser.close()
    }
})()
```

I don't mind creating a PR to fix it but will need some guidance and hints.

**Comment by esakal** [comment]
Hello @konfortes I'm glad to hear that you find this repo effective 👍 

Obviously we can try to find a better solution or understand the root cause if the issue, but your workaround is good enough and if it does the job you can create a PR and we will merge it.

As I dont have Beinleumi I'm not able to run this scraper but obviously adding this timeout cannot harm others.

**Comment by konfortes** [comment]
Hey @esakal @LiranBri 
I tested the change locally and it fixes the issue.
Created [this PR](https://github.com/eshaham/israeli-bank-scrapers/pull/699) (please link the issue):

**Comment by konfortes** [comment]
@esakal any idea why there was no release created for my fix merge?
Looking at the release workflow definition it seems like each push to master should trigger a release. What am I missing?
Saw this log in the [action](https://github.com/eshaham/israeli-bank-scrapers/runs/7062707172?check_suite_focus=true):
```
[6:47:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:47:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: no release
[6:47:00 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:47:00 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

**Comment by esakal** [comment]
@konfortes yes it is a typo mistake, I accidentally prefixed the commit message with `Fix` instead of `fix` (capital letter F) so semantic release didn't detect it as a valid change.

Will resolve it soon
