### ISSUE TITLE
Logged into union bank but scraping doesn't work

### ISSUE THREAD

**Issue by YehonatanGitHub** [eshaham/israeli-bank-scrapers#701]
Hi, I successfully logged into union bank but then nothing happens and the system times out. 

here is the console.log(scrapeResult);
{
  success: false,
  errorType: 'GENERIC',
  errorMessage: 'waiting for selector `#signoff` failed: timeout 30000ms exceeded'
}

here is how I set the options: 

const options = {
      companyId: CompanyTypes.union,
      verbose: true,
      startDate: new Date('2022-02-01'),
      combineInstallments: false,
      showBrowser: true,
    };

using node v14.15.1
Thanks in advance

**Comment by esakal** [comment]
Hello,
Sorry I don't have an account there so I cannot verify the validity of the scraper. But you can run the diagnostics logs it might help figuring out where is the issue.

You should run the node script with the env DEBUG=israeli-bank-scrapers:*

I hope it might help identify the root cause

**Comment by esakal** [comment]
@YehonatanGitHub please re-open the ticket if it is still relevant
