### ISSUE TITLE
Other financial institutes scrapers

### ISSUE THREAD

**Issue by doron-cohen** [eshaham/israeli-bank-scrapers#706]
Hi,
I just found out about this project, so first of all thank you for maintaining it.
I would like to ask if you know of any scrapers for other financial institutes that offer services like Pensia, Keren Hishtalmut, stock exchange investment etc. If not, do you consider supporting these?

**Comment by doron-cohen** [comment]
About collaborating, I'll be glad to do so! I  can start investing time in this only after the summer vacation but let's talk.

**Comment by gilgardosh** [comment]
> It's hell

you're being polite here.
amazing that you are into it and willing to get your hands dirty 😄 ping me whenever you want to dive in

**Comment by erikash** [comment]
Hi guys,
I'm one of the founders of `www.mukdam.co.il`.
We're a digital insurance agency with aspirations for becoming a digital family office in the future.

I started the company for the same frustrations you're experiencing with data and tracking - I also use a google sheet - a pretty good one that sends monthly reports via email and tracks your net worth over time...

What can we offer right now?
If you nominate us as your insurance agent (will not effect any existing agreements you have with any existing pension funds, provident funds, advanced study funds), we'll be able to fetch your Masleka every month for pretty much free and provide an API which can be consumed with Integromat (Now make), Zapier or any other automation tools which can push it Google Sheets or any other app...

Sounds interesting? feel free to PM me or click the contact us via WhatsApp in our website at `www.mukdam.co.il`.

**Comment by Urigo** [comment]
@erikash is any of the work that you are doing open source?

**Comment by erikash** [comment]
Hi @Urigo ,
Not yet but would be happy to open source parts of it!

**Comment by Urigo** [comment]
what parts?  we would love to help with that!

**Comment by erikash** [comment]
Let's talk :)
I've send you an email

**Comment by doron-cohen** [comment]
@erikash count me in. Maybe we can talk over the project's Discord? Or somewhere else we can collaborate?

**Comment by erikash** [comment]
Sounds great @doron-cohen !
Didn't find the project's discord server.. 😬
My email is: erik@mukdam.co.il
Shoot me an email and we'll start the conversation 🙏

**Comment by erikash** [comment]
@doron-cohen still waiting for that email 😅

**Comment by doron-cohen** [comment]
@erikash sending one today

**Comment by esakal** [comment]
@doron-cohen feel free to reopen with comment if you would like to continue this discussion
