### ISSUE TITLE
American Express scraper throws SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by LiranBri** [eshaham/israeli-bank-scrapers#714]
Hi,
I see that the American Express scraper is throwing
```
error: GENERIC: Evaluation failed: SyntaxError: Unexpected end of JSON input
    at _puppeteer_evaluation_script_:16:26

```

does it happen to more people?

**Comment by esakal** [comment]
It doesn't happen to me. Did you try re-installing the library? did you update recently to latest?
