### ISSUE TITLE
ISA CAL - "Navigation timeout of 30000 ms exceeded"

### ISSUE THREAD

**Issue by agammyshhay** [eshaham/israeli-bank-scrapers#719]
hi,

the issue occur every day in the last week.

thanks

**Comment by asamarom** [comment]
same for me.

**Comment by esakal** [comment]
Hi, as this is an old issue, is it still happening to you? if so are you using the latest version? @agammyshhay  @asamarom ?

**Comment by erikash** [comment]
You should be able to extend it if you have poor wifi now with the `defaultTimeout` option.

**Comment by agammyshhay** [comment]
hi,
yeah it start hapenning again in the last couple of weeks - i think its since  v2.1.0 -  im using CASPION, so i get everythng in delay.
its occur also for FIBI
