### ISSUE TITLE
Future (Abroad) transactions to be processed in future months are missing in visaCal

### ISSUE THREAD

**Issue by erikash** [eshaham/israeli-bank-scrapers#721]
Hi,
So this is not a new issue (for me) but it annoyed me enough to raise it here and maybe to finally solve it :)

In visa cal when you "show transactions by process date" you can't choose a future month later than the next immediate month (i.e the latest is October when i'm viewing my transactions in Sep)
<img width="678" alt="image" src="https://user-images.githubusercontent.com/140349/190680151-6abb6523-9ef9-4a8e-aa52-26c4708d828b.png">

Since my abroad transactions are processed two months later (Sep transactions will only be visible in December, same as July transactions are only visible in October)
<img width="722" alt="Screen Shot 2022-09-16 at 21 54 28" src="https://user-images.githubusercontent.com/140349/190680562-159759db-06a5-4b39-9be5-a18cb4f40ec5.png">

As you can see using the "show transactions by processed date" option, there is no way to view the abroad transactions I did on August and September... 

But... using the "show transactions by transaction date option" I can see abroad transactions BUT not the installment transactions 🤦 
<img width="728" alt="Screen Shot 2022-09-16 at 23 00 53" src="https://user-images.githubusercontent.com/140349/190681397-0cc9e783-4c45-47ae-b092-53a496a38ac4.png">

@esakal what do you say we extend the scraper to scrape transactions using the "show transactions by transaction date option" *in addition to* the "show transactions by processed date" and then deduplicate the transactions? that way we'll at least see the whole picture...

Other suggestions?

**Comment by esakal** [comment]
Hi @erikash sorry that it took me that long to reply.

I'm familiar with the missing installment transactions when using process dates. I actually tried to implement the scraper originally with the process date and switched eventually to process date.

We have in options the property `futureMonthsToScrape` that is used already in max, amex and isracard. It sounds like you can extend the visa scraper like you suggested to consolidate information from both processed date and transaction date.

I'm not sure if the best approach would be to:
1. scrape all the installments like today by processed date.
2. scrape all other transactions by transaction date

Or to deduplicate the transactions like you mentioned.

Both should work, the second is more closer to what we do today while the first sounds more robust assuming that only installments are missing. So I'm ok with both by favor a bit the second one.

what do you think?

**Comment by erikash** [comment]
Thanks Eran,
Now It's my turn to be a bit busy...

Hope to have some time to work on this next week :)

Happy holidays!
Erik.

**Comment by erikash** [comment]
Didn't have much time.. but I really liked your two step approach without deduplication (except for the combined installment transaction).

Hope to get to this next Saturday 🙏

**Comment by itairaz1** [comment]
setting `enableTransactionsFilterByDate` to false should resolve this

**Comment by erikash** [comment]
Congrats @orzarchi - your PR https://github.com/eshaham/israeli-bank-scrapers/pull/777 seems to solve this issue as well :)
