### ISSUE TITLE
Import from Leumi - Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by shahar4499** [eshaham/israeli-bank-scrapers#722]
Just tested the fix v2.1.1, and the login still fails for some reason. Now the error is more ambiguous: `Navigation timeout of 30000 ms exceeded`. So it's not clear what it's waiting for.
When looking at the browser it doesn't fill in the user+pass and just stays stuck on the login page like this:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9296022/191232184-31fdb61f-a754-4a01-8e7a-47e3712d7741.png">

**Comment by baruchiro** [comment]
Hi @shahar4499, do you want to try to debug it? Do you have the knowledge of that?

**Comment by shahar4499** [comment]
OK, so apparently the went back to the previous implementation of their login page 🤦‍♂️ 
So, this commit: https://github.com/eshaham/israeli-bank-scrapers/commit/962e0b40d545b6f48035b5e1826826dc6e91647a should partially be reverted. I debugged the scraper after reverting the file and it succeeded with the login.
BUT, in `waitForPostLogin` it still seems to be stuck, with or without this latest commit.
So the breaking changes that Leumi did might be more complicated than expected...
Will continue to debug in a later time.

**Comment by esakal** [comment]
@shahar4499 please check again, for me it works with the latest scrapers

**Comment by esakal** [comment]
@shanigad I'm closing this one as it was not answered in a while. If still relevant please create a new issue
