### ISSUE TITLE
Error connecting to Bank Hapoalim

### ISSUE THREAD

**Issue by MusiCode1** [eshaham/israeli-bank-scrapers#723]
Hello.
Today I tried this project for the first time, with my bank, Bank Hapoalim.
But there is an error...
The error is `UNKNOWN_ERROR`.
From digging in the debugger, it seems that the URL address of the Bank Hapoalim home page is not updated.

My URL is
https://login.bankhapoalim.co.il/ng-portals/rb/he/current-account/transactions
And this address does not appear in this list:

```
function getPossibleLoginResults(baseUrl) {
  const urls = {};
  urls[_baseScraperWithBrowser.LoginResults.Success] = [`${baseUrl}/portalserver/HomePage`, `${baseUrl}/ng-portals-bt/rb/he/homepage`, `${baseUrl}/ng-portals/ rb/he/homepage`];
  urls[_baseScraperWithBrowser.LoginResults.InvalidPassword] = [`${baseUrl}/AUTHENTICATE/LOGON?flow=AUTHENTICATE&state=LOGON&errorcode=1.6&callme=false`];
  urls[_baseScraperWithBrowser.LoginResults.ChangePassword] = [`${baseUrl}/MCP/START?flow=MCP&state=START&expiredDate=null`, /\/ABOUTTOEXPIRE\/START/i];
  return urls;
}
```

Translated by machine translation.
Sorry...

_(Is it possible to write here in Hebrew?)_

**Comment by MusiCode1** [comment]
Now I think that it is because I configured that after logging in I will be shown a page of recent actions, and not the home page.
What now, without changing this definition?

**Comment by esakal** [comment]
Hello,
I don't have account in bank hapoalim so I cannot assist extending the scraper. As I see, you can:
1. change the definition back.
2. use the test pages to support also the recent actions page and create a PR.
3. wait for someone here that might have Hapoalim to reply and assist.
