### ISSUE TITLE
Do you have Expo react native support?

### ISSUE THREAD

**Issue by eliranma** [eshaham/israeli-bank-scrapers#731]
I tried to import your package in my app but I got 
'Unable to resolve "israeli-bank-scrapers" from "functions.js" '
I just Copy-Paste from the example...
`import { CompanyTypes, createScraper } from 'israeli-bank-scrapers';`

**Comment by esakal** [comment]
Hi, I never tried the library with React Native so I don't know how to answer your question... sorry :/
