### ISSUE TITLE
Harel and 2FA

### ISSUE THREAD

**Issue by mnavon** [eshaham/israeli-bank-scrapers#734]
Hi
I would like to write a new scraper for Harel.
But Harel login works with 2FA and sends code via SMS.
Is there a way to overcome this issue?

**Comment by esakal** [comment]
Hi @mnavon this is a great question. 
I know there are some approaches to this issue, like creating a pub/sub based async communication to ask the application/service who is using our library to provide such an information.

It will change the methodology we had so far by not blocking the scrapping process, but it might be inevitable. 

@eshaham  @erikash  @itairaz1  wdyt?

**Comment by erikash** [comment]
This could be an opportunity to discuss the overall design - maybe we should create a new AsyncBaseScraper and let the consuming code call the login and scrape on it's own (also to fill in the OTP)

@mnavon @esakal @itairaz1  wanna jump on a quick zoom call / huddle to discuss?

**Comment by itairaz1** [comment]
Hi,
IMO, since this is lib that uses by other apps, it need to be opened to any architecture that will be implemented by the apps the uses it.
So in this case, we can do simple solution like providing a callback function, this will provide other apps to implement any approach they choose.
The callback function can be provided in the options/configs section, and if 2FA is required and no callback is provided, and error will be raise.
@mnavon @esakal @itairaz1 @erikash  WDYT?

**Comment by esakal** [comment]
I believe a callback is a good options.
1. a scraper can support 2FA.
2. if reached a 2FA flow and options has a callback, **something like 'on2FAScrapping'**, it will be called in async way.
3. if the callback is not provided, **a new type of error (something like `ScraperErrorTypes.2FASupportRequested** will be returned to the implementor indicated that 2fa callback is required to complete the process.
4. in the documentation we will advice to extend the timeout period if they expect to have 2fa flow in their use-case. The timeout option is general to all scrapers but I believe it is ok
5. Edge case concern, the puppeteer will reach timeout before getting a response of the 2FA. I believe it is ok and will not create a memory leak, wdyt?

a suggestion to the `on2FAScrapping` signature:
```
on2FAScrapping?: (companyId: CompanyTypes) => Promise<{string}>
```

What do you think?

**Comment by itairaz1** [comment]
@esakal Yeah... it make sense

**Comment by esakal** [comment]
@mnavon feel free to introduce the 2FA concept together with the Harel scraper. You can follow the requirements in https://github.com/eshaham/israeli-bank-scrapers/issues/734#issuecomment-1299677087
