### ISSUE TITLE
[leumi] Slow edge device fail scrap

### ISSUE THREAD

**Issue by itairaz1** [eshaham/israeli-bank-scrapers#739]
Running latest version (3.1.2) with following config:
```       
combineInstallments: false,
showBrowser: false,
```
I'm keep getting the following error only on slow edge device (Raspberry PI) while scraping leumi
`failed with type GENERIC: waiting for XPath ``//div[contains(string(),"אחד או יותר מפרטי ההזדהות שמסרת שגויים. ניתן לנסות שוב")]`` failed: timeout 30000ms exceed`
Locally (in high end device) I don't get this error, with the same credentials.
I think I didn't have this issue in older version, but I can't ensure

**Comment by liranay** [comment]
Hi
In order to fix the issue in my raspberry pie, I manually changed the timeout in the "node_modules/israeli-bank-scrapers/lib/scrapers/leumi.js" file
from 300000 ms to 0 (unlimited), it solved the issue
Maybe we can think about making the timeout field configurable

**Comment by itairaz1** [comment]
Thanks @liranay 
I forgot to update that I did several scrapings in parallel, when I changed it to one by one it solves the issue
Also, I implemented timeout to be configured, you can pass it through `options` argument.
I'm closing this issue
