### ISSUE TITLE
[Discussion] Implement extra scrapping for category

### ISSUE THREAD

**Issue by itairaz1** [eshaham/israeli-bank-scrapers#740]
Hi,
I've started implementing scrapping categories (Maybe more information) per transaction (currently for isracard)
This requires perform extra click for every transaction
It will work only when specific configuration will turned on.
Any insides? anyone tried doing it already?

@eshaham @esakal @erikash

**Comment by itairaz1** [comment]
@eshaham @esakal @erikash I made the changes in [PR](https://github.com/eshaham/israeli-bank-scrapers/pull/741), can you please review it? If everything ok and agreed, I can proceed with visa cal or/and add more data to the result set.

**Comment by esakal** [comment]
@itairaz1 would you like to keep this one open while you implement visa cal? We can instead close this one and just open a PR when you have one. wdyt?

**Comment by itairaz1** [comment]
Sure, np. But it might take a while (another week or 2)

**Comment by esakal** [comment]
great. when ready just create a PR
