### ISSUE TITLE
Is there a way to get the amount of money in the bank account?

### ISSUE THREAD

**Issue by sdimantsd** [eshaham/israeli-bank-scrapers#743]
I get only the transactions...
Thanks :-D

**Comment by sdimantsd** [comment]
In Yahav you have balance?
I don't get it, but it might israel-finance-telegram-bot repo fault.

**Comment by esakal** [comment]
@sdimantsd  Yahav scraper implementation doesn't seem to have balance extraction thus you get `undefined`. Feel free to create a PR and contribute. see https://github.com/eshaham/israeli-bank-scrapers/blob/master/CONTRIBUTING.md

**Comment by sdimantsd** [comment]
OK. Thanks
