### ISSUE TITLE
Credit funding on credit cards

### ISSUE THREAD

**Issue by tounano** [eshaham/israeli-bank-scrapers#75]
Hi,

I'm planning to use this library for accounting automation.

In order to do accounting automation, you need to include the transactions that come from your bank account.

For most of you it's on a fixed date. For businesses it might be several times a months, to release some credit in the card.

I'm planning to add this feature to Amex/Mastercard.

Since it's not my project, I wanna know what @eshaham thinks of that, and how we can embed it, without hurting his vision about the project.

I was thinking about adding some sort of an option.

What do you think?

**Comment by eshaham** [comment]
@tounano how does it look on the statement in the credit card website?
does it appear as an additional transaction with a different type?
any type you can attach a relevant screenshot so it is easier to understand what you mean?

**Comment by tounano** [comment]
@eshaham Here's how it looks like: https://d.pr/i/Csht88

It's the black ones that say: Total for date.

Now with Amex/Mastercard it would say total for date for future dates as well, but future dates might be ignored.

In the REST calls these transactions don't have "misparRutz" or something like that.

Basically, from accounting stand point, when you add all the statement lines one to another, at the end of your fiscal month, you should get zero at the balance.

**Comment by eshaham** [comment]
@tounano this is a tough one, I'm not sure how to approach it.
I'm pretty sure we shouldn't include transactions coming from the bank account, but rather manage the balance / credit utilization.
see the discussion here: https://github.com/eshaham/israeli-bank-scrapers/issues/76

do you think the account summary could somehow answer your needs?
