### ISSUE TITLE
No transactions from cal importer

### ISSUE THREAD

**Issue by Nitaym** [eshaham/israeli-bank-scrapers#753]
Hey,

The cal importer is not importing anything. I've verified I have transactions in the CC report - And chromium shows transactions (visually) as well. But nothing is getting to the reports.

I've ran the scraper via caspion (version 1.9.1, but happened on previous versions as well)

**Comment by esakal** [comment]
Hi @Nitaym 
Can you check it with caspion developers? I'm running the test of visa cal on the repo and gets results
![CleanShot 2023-01-23 at 17 22 40@2x](https://user-images.githubusercontent.com/4751797/214078190-2f54acfb-9c05-48c7-9966-2b151838d213.jpg)

**Comment by esakal** [comment]
@Nitaym  any update?

**Comment by esakal** [comment]
@Nitaym feel free to open it if still relevant
