### ISSUE TITLE
TypeScript upgrade

### ISSUE THREAD

**Issue by sagiba** [eshaham/israeli-bank-scrapers#758]
I am working on a private fork of the repo with some changes (will hopefully send a PR for some of them in the near future), and noticed that the TypeScript version that is used, 3.9.10, is very ancient. This is causing issues with bringing in some updated dependencies.

Any objection with trying to upgrade to a more modern version of TypeScript?

**Comment by esakal** [comment]
Hi @sagiba sure, feel free to try upgrading. If it doesn't break anything we can merge it. If it does then please share what is broken or provide a draft PR to experiment with
