### ISSUE TITLE
Max not working, always get error "בשל מספר ניסיונות לא טובים, נבקש למלא את מספר תעודת הזהות שלך"

### ISSUE THREAD

**Issue by myakove** [eshaham/israeli-bank-scrapers#759]
Using the sample code from doc:

```
import { CompanyTypes, createScraper } from "israeli-bank-scrapers";

(async function () {
  try {
    // read documentation below for available options
    const options = {
      companyId: CompanyTypes.max,
      startDate: new Date("2020-05-01"),
      combineInstallments: false,
      showBrowser: true,
    };

    // read documentation below for information about credentials
    const credentials = {
      username: "my email",
      password: "my password",
    };

    const scraper = createScraper(options);
    const scrapeResult = await scraper.scrape(credentials);

    if (scrapeResult.success) {
      scrapeResult.accounts.forEach((account) => {
        console.log(
          `found ${account.txns.length} transactions for account number ${account.accountNumber}`
        );
      });
    } else {
      throw new Error(scrapeResult.errorType);
    }
  } catch (e) {
    console.error(`scraping failed for the following reason: ${e.message}`);
  }
})();

```

Always get error in the browser:
```
בשל מספר ניסיונות לא טובים, נבקש למלא את מספר תעודת הזהות שלך

```

Happens always even right after reset password on the website.

**Comment by OfekA** [comment]
Can confirm, I also have this issue.

**Comment by esakal** [comment]
@myakove hi, can you verify the credentials you provide?
Also I recommend to try them manually and check maybe you are getting a popup that you should dismiss once to make it work.
I'm running the max scraper daily and it works for me with the last version

**Comment by myakove** [comment]
Checked many times
Reset my password, login via browser to see that I can login with the new password and after confirm that all works run the script

And got the error on the first try.

**Comment by myakove** [comment]
Seems like it's not related to this repo.
Even when I try to log in again from the browser after reset the password, I get this error.

Closing this issue, will reopen if needed.
