### ISSUE TITLE
Cal site updated, scraper is failing

### ISSUE THREAD

**Issue by sohodf** [eshaham/israeli-bank-scrapers#763]
Cal site has new design, and the scraper made for it is failing. 
Any intention to fix it?

**Comment by davlasry** [comment]
same thing for me

**Comment by erikash** [comment]
Finally some JSON...
![image](https://user-images.githubusercontent.com/140349/228134173-e7e11f27-d3bf-4eb6-a0af-e745b6db91f9.png)

**Comment by baruchiro** [comment]
@erikash Are you working on it?

**Comment by erikash** [comment]
@baruchiro - not actively - I'll try to take a look at it over the weekend.. if anyone else is available please go ahead and update here

**Comment by baruchiro** [comment]
I'm taking it with the [Open Source Party](https://www.linkedin.com/events/7046778125128507394)

**Comment by erikash** [comment]
@baruchiro amazing!
Feel free to tag me so I can review / test it with my account :)

**Comment by baruchiro** [comment]
Started on https://github.com/baruchiro/israeli-bank-scrapers/tree/baruchiro/Cal-site-updated-scraper-is-failing

I only managed to handle the introduction page. Now we need to "fetch within the page".

**Comment by LiranBri** [comment]
Reproduced to me as well

**Comment by baruchiro** [comment]
One more step. All we need now is to fetch the next request for each month and get the transactions from the response.

```
curl 'https://api.cal-online.co.il/Transactions/api/transactionsDetails/getCardTransactionsDetails' -H 'Authorization: ${Authorization}
```

You can continue my branch [here](https://github.com/baruchiro/israeli-bank-scrapers/tree/baruchiro/Cal-site-updated-scraper-is-failing). If you taking this please let me know.

**Comment by liranelisha** [comment]
just found this package when i had the same issue with them
i've solved it, but i use playwright so i won't be of much service to you...
however, wanted to ask if you ran into the issue when trying to log in that the site actively trying to prevent clicking on the login button?

**Comment by sohodf** [comment]
Hi guys, thank you for your great work. Is the PR ready? Are you planning on merging it soon?

**Comment by baruchiro** [comment]
@sohodf Still in progress, you're welcome to continue my work or help me here: https://github.com/eshaham/israeli-bank-scrapers/pull/767#discussion_r1157172834

**Comment by sohodf** [comment]
@baruchiro  - unfortunately, I'm not familiar with Node.js.
Didn't mean to come off demanding or anything, just wanted to know if it's WIP, at all or not.
I appreciate this project very much and all the great work you guys are doing.
However, I'm just a user in this context.
