### ISSUE TITLE
Open banking laws

### ISSUE THREAD

**Issue by davlasry** [eshaham/israeli-bank-scrapers#764]
I am not super familiar with this topic but as far as I understand some banks can now share information with external services through an API.

Is this something that is open to anyone or only to authorized institutions/companies?

**Comment by erikash** [comment]
Only regulated and authorized companies

**Comment by esakal** [comment]
I hope an authorized company will provide an API with low cost so we will be able to use it in the future instead. But for now as @erikash mentioned it is not relevant to this project

**Comment by DavidConnack** [comment]
@esakal any idea if the landscape of this has changed at all?
Something like whatever [riseup](https://www.riseup.co.il/) uses?
Having something like https://gocardless.com/bank-account-data/ but for Israel.

**Comment by D3SL** [comment]
It hasn't. Like a lot of things in Israel it was a good idea with crippled implementation. Open Banking access requires getting multiple certifications from the government. It would have been better if the law mandated providing a secure secret based access system to users instead.

**Comment by DavidConnack** [comment]
That's unfortunate.
