### ISSUE TITLE
Incorrect mapping of transaction identifier in Poalim bank scraper

### ISSUE THREAD

**Issue by mnavon** [eshaham/israeli-bank-scrapers#768]
Hi everyone.

I have been using the Poalim bank scraper to scrape my account transactions, and I noticed that there is an issue with the mapping of the transaction identifier. Currently, the identifier being used is the institution code (`referenceNumber` from Poalim API), which is not the transaction identifier.

To get the correct transaction identifier, the scraper needs to drill down to every transaction and get the full details by calling the route under "pfmDetails" (The route is given for every transaction from the get transaction list API call that we use). However, this means that there could potentially be hundreds of API calls, which could impact performance.

I am seeking advice on whether this approach is acceptable, or if there is a more efficient way to retrieve the correct transaction identifier.

Thank you.

**Comment by esakal** [comment]
Hi, I don't have bank ha poalim account so I cannot play with their site.  

We added this option https://github.com/eshaham/israeli-bank-scrapers/blob/81cb33f789183d85659225e48be8ed6eb7060749/src/scrapers/interface.ts#L120 to let user ask for additional information that requires intensive requests to get additional information. So you can use that field and create a PR where when user sets this flag you perform the additional requests to get the transaction id.

I hope it helps

**Comment by mnavon** [comment]
@esakal  When using this flag, should I replace the identifier field from code mosad to the real transaction ID?
Or to use other field?

**Comment by mnavon** [comment]
I'll appreciate if you could review my PR https://github.com/eshaham/israeli-bank-scrapers/pull/787
