### ISSUE TITLE
Visa Cal wrong day of transaction, and missing fields

### ISSUE THREAD

**Issue by baruchiro** [eshaham/israeli-bank-scrapers#781]
Hi, compared to the previous version of Visa Cal, I see a few differences:

![image](https://user-images.githubusercontent.com/17686879/233826715-83a23bf9-2150-440b-9bc3-e9ac845b5897.png)

- [ ] The order of the fields was changed.
- [ ] The `chargedCurrency`, `identifier`, and `memo` are missings.
- [ ] The `date` and `processedDate` are different in one day, but according to the website, maybe now it is the right date:  
  ![image](https://user-images.githubusercontent.com/17686879/233826901-f04e20be-1ea9-49c1-ae28-e827fab223fc.png)

**Comment by baruchiro** [comment]
@erikash Please see if you can help with the missing fields 🙏

**Comment by daniel-hauser** [comment]
@baruchiro Both dates are "23/02/2023".
The new site has the transaction time while the old scraper had the start of the day - `00:00` (== 22:00 in GMT/UTC)

```
> new Date("2023-02-22T22:00:00Z")
Thu Feb 23 2023 00:00:00 GMT+0200 (Israel Standard Time)
```

**Comment by daniel-hauser** [comment]
Regarding the `date` field -
I think we should have the more exact time even though its part of the hash (moneyman has the same hash as caspion) and pay the price of duplications for the short term as now we have better hashes (2 transactions in the same place in the same day for the same amount now have different hashes).

**Comment by erikash** [comment]
The date semantics changed though... it used to be UTC (hence the the -2 hours causing "22:00 of the previous day")

WDYS about parsing the dates as IST / IDT? 

It will break your hashes again but I think it's worth it...

**Comment by erikash** [comment]
@baruchiro @daniel-hauser ?

**Comment by daniel-hauser** [comment]
@erikash 
The type of `data` is an ISO date string.
As long as the string is valid, I have no hard opinion on the time zone in it (`"2023-02-22T22:00:00Z"` === `"2023-02-23T00:00:00+02:00"`)

@baruchiro
If you parse the date string as I do in moneyman, you can then format it when hashing.

See [daniel-hauser/moneyman/blob/main/src/storage/utils.ts](github.com/daniel-hauser/moneyman/blob/c4d03fc195688d42ff434bbe1c2e4b689666d0a2/src/storage/utils.ts?plain=1#L10):
```typescript
export function transactionHash(
  tx: Transaction,
  companyId: CompanyTypes,
  accountNumber: string
) {
  const date = roundToNearestMinutes(parseISO(tx.date)).toISOString();
  const parts = [
    date,
    tx.chargedAmount,
    tx.description,
    tx.memo,
    companyId,
    accountNumber,
  ];

  return parts.map((p) => String(p ?? "")).join("_");
}
```

**Comment by erikash** [comment]
Actually I suspect @baruchiro you might have a bug - I'm parsing the dates correctly assuming `Asia/Jerusalem` timezone in my package consuming `israeli-bank-scrapers`
https://github.com/orzarchi/israeli-finance-scraper/blob/master/src/runCommand.ts#L12

**Comment by erikash** [comment]
@daniel-hauser take a closer look at his screenshot - specifically the processed date in the first vs the second one - the dates are different (assuming both are UTC)

**Comment by daniel-hauser** [comment]
> @daniel-hauser take a closer look at his screenshot - specifically the processed date in the first vs the second one - the dates are different (assuming both are UTC)

Oh, I was focused on the `date`, missed out the issue in `processedDate`.

**Comment by erikash** [comment]
> @erikash The type of `data` is an ISO date string. As long as the string is valid, I have no hard opinion on the time zone in it (`"2023-02-22T22:00:00Z"` === `"2023-02-23T00:00:00+02:00"`)
> 
> @baruchiro If you parse the date string as I do in moneyman, you can then format it when hashing.
> 
> See [daniel-hauser/moneyman/blob/main/src/storage/utils.ts](github.com/daniel-hauser/moneyman/blob/c4d03fc195688d42ff434bbe1c2e4b689666d0a2/src/storage/utils.ts?plain=1#L10):
> 
> ```ts
> export function transactionHash(
>   tx: Transaction,
>   companyId: CompanyTypes,
>   accountNumber: string
> ) {
>   const date = roundToNearestMinutes(parseISO(tx.date)).toISOString();
>   const parts = [
>     date,
>     tx.chargedAmount,
>     tx.description,
>     tx.memo,
>     companyId,
>     accountNumber,
>   ];
> 
>   return parts.map((p) => String(p ?? "")).join("_");
> }
> ```

The link here is broken - I suggest you should check that you're parsing with the correct timezone as well

**Comment by daniel-hauser** [comment]
> The link here is broken - I suggest you should check that you're parsing with the correct timezone as well

Fixed the link.

When scraping, [I set](https://github.com/daniel-hauser/moneyman/blob/c4d03fc195688d42ff434bbe1c2e4b689666d0a2/.github/workflows/scrape.yml#L51) the `TZ` env var to `"Asia/Jerusalem"`

**Comment by daniel-hauser** [comment]
@erikash 
The best fix for `processedDate` IMHO is to covert to a "real" ISO date:

In [src/scrapers/visa-cal.ts](https://github.com/eshaham/israeli-bank-scrapers/blob/580cc03173268ca86620df26cbb8a05401c88f52/src/scrapers/visa-cal.ts#L207)
```diff
- processedDate: transaction.debCrdDate,
+ processedDate: new Date(transaction.debCrdDate).toISOString(),
```

This will still assume that the system TZ is correct, but at least the field will have the timezone explicitly

**Comment by roisec** [comment]
Any news? @erikash

**Comment by baruchiro** [comment]
Actually, I didn't understand what are the consequences of this thread 🥴

**Comment by baruchiro** [comment]
Here is the current state of `israeli-bank-scrapers`:
![image](https://user-images.githubusercontent.com/17686879/235355298-52d24995-ba89-472c-bf61-fed789fb653e.png)



![image](https://user-images.githubusercontent.com/17686879/235355243-0d04f500-b8ea-4615-aa77-952926782af9.png)

From what I see here, I understand the confusion because the `date` is represented as ISO date (UTC), but the `processedDate` is saved as a local date.

If so, we just need to align them first. And as I see in Leumi and Mizrahi, they are returning ISO string, so we will do it here as a first step.
