### ISSUE TITLE
CAL scraper should retrieve pending transcations

### ISSUE THREAD

**Issue by galbarm** [eshaham/israeli-bank-scrapers#791]
CAL launched a new website this week and surprisingly the scraper is still working.

Previously CAL showed only completed transactions but now on the new website they also show pending transactions.
These pending transactions are currently not returned by the scraper.

The scraper should be updated to retrieve the pending transactions as well.

**Comment by niv280** [comment]
HI, it's not working for me, it's stuck after the login when the new UI ad pop and then I get Timeout error.
You didn't encounter this?

**Comment by galbarm** [comment]
> HI, it's not working for me, it's stuck after the login when the new UI ad pop and then I get Timeout error. You didn't encounter this?

No.
Surprisingly it's working properly for me.
I even set `showBrowser: true` to verify that it is the new website which gets opened.

**Comment by esakal** [comment]
Hi @galbarm @niv280 
Is this issue still relevant or can we close it?

**Comment by galbarm** [comment]
@esakal hi, please don't close.
The issue is relevant and I will create a PR for it soon.

**Comment by niv280** [comment]
For me it's not working at all, I'm getting Timeout error inside getLoginFrame func.
Should I open separate issue about it?

**Comment by galbarm** [comment]
@niv280 yes. this issue is only for supporting pending transactions

**Comment by gbarmashiahflir** [comment]
@amir-daniel it has a PR waiting for several month:
https://github.com/eshaham/israeli-bank-scrapers/pull/794
