### ISSUE TITLE
CAL scraper failed in new website

### ISSUE THREAD

**Issue by niv280** [eshaham/israeli-bank-scrapers#793]
Hi,
I'm getting Timeout error while using visacal scraper.
It's look that the error happened inside getLoginFrame, when the scraper don't found the login frame.

I'm not got good knowledge in scraping but it's seems to me that visa cal update their website, and when I tried to use the scraper with showBrowser it's look that there is some kind of popup window that might block the scraper from moving on to the transactions area.

**Comment by baruchiro** [comment]
VisaCal is working well for me

**Comment by niv280** [comment]
That can be different between different users?

**Comment by gbarmashiahflir** [comment]
Maybe different OS? for me this is working well on Windows

**Comment by galbarm** [comment]
Maybe different OS? for me this is working well on Windows

**Comment by niv280** [comment]
I'm running it in ubuntu, do you think that can cause problems?
I remember now, that visa cal worked for me in windows when I used Caspion a while ago

**Comment by baruchiro** [comment]
I tried to close this banner here:
https://github.com/eshaham/israeli-bank-scrapers/blob/2f9d73638b641c2c770f104a7887f7db12800cee/src/scrapers/visa-cal.ts#L296-L306

**Comment by gczobel** [comment]
The same happens to me today, running on ubuntu.
I entered the website in my browser and a change password was required (that was not detected by the scraper). After that, the same screen about the new website was displayed... so probably a combination of the two?
