### ISSUE TITLE
visa-cal scraper incorrectly parsing credits

### ISSUE THREAD

**Issue by chaosite** [eshaham/israeli-bank-scrapers#807]
I use moneyman. When a transaction is a credit, I'm seeing the scraper return a negative `chargedAmount` and a positive `originalAmount`.

I expect them both to be positive in case of a credit (are there any cases where they should have a different sign?)

I'm seeing this only with visa-cal, the other scrapers seem fine.

**Comment by itamarco** [comment]
Happen also in my side with visa-cal.
Plus-  refunds that originally in dollar are missing from `txns`

**Comment by itamarco** [comment]
Opened this PR to fix both issues 
https://github.com/eshaham/israeli-bank-scrapers/pull/808
