### ISSUE TITLE
Can I use this project in google scripts?

### ISSUE THREAD

**Issue by sdimantsd** [eshaham/israeli-bank-scrapers#816]
If so, 
How can I do it?

**Comment by daniel-hauser** [comment]
There's no way to use chromium in Google App Scripts, therefore no way to use puppeteer.

If you want a way to run scrapers automatically in the cloud you can try [daniel-hauser/moneyman](https://github.com/daniel-hauser/moneyman)

**Comment by sdimantsd** [comment]
OK. Thanks
