### ISSUE TITLE
Max site never stop loading

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#817]
Hi,
Someone else have this issue? I cannot import any transaction from MAX. Making the browser visible, I see the page never finish loading until timeout is received.
Same happen from time to time in my desktop... any idea how to solve this?

**Comment by felipegrin** [comment]
See here: https://github.com/eshaham/israeli-bank-scrapers/issues/814

**Comment by gczobel** [comment]
thanks @felipegrin
