### ISSUE TITLE
Add an extra description property (Memo) for transactions

### ISSUE THREAD

**Issue by esakal** [eshaham/israeli-bank-scrapers#83]
@eshaham you created an essential project that is missing in the Israeli financial atmosphere! I really liked the way you scaffold the project and provided an infrastructure that is easy to follow and extend.

I'm working on a crawler for the Leumi Bank where they provide an extra field relevant to transfers into your account. This field describe the actual payee and it is an essential field for many transfer transactions like bit, הוראות קבע, salaries, internet wired transfers etc. Bank Hapoalim also exposes this information and I believe it is available for the others banking institutes as-well. 

I think the transaction should have an optional field named 'memo' of type string where we can provide this information.

I would appreciate your insights on that matter. 
Eran.

**Comment by eshaham** [comment]
@esakal yes, it certainly makes sense, and `memo` as the field name sounds right.
Having said that, I would love to apply it as once for all banks, so it will be a joint effort.

If I understand correctly, you're working on the Leumi Bank scraper to be added here? If so, I would suggest separating the addition of the new field `memo` from your work on this scraper.

Btw, for Leumi Bank, @Urigo has mentioned he has something in place (unrelated to this repo), so it might be helpful for you to checkout his repo https://github.com/Urigo/leumi-leumicard-bank-data-scraper. Also, I think @ifeins started working on adding it here, so might be helpful to sync.

**Comment by esakal** [comment]
@eshaham great lets do it. I commented 3 places in the PR for bank leumi #86  so you will be able to easily plug it back.

@ifeins, feel free to check my work in #86 . I added information about the scraper in the PR description. 

@Urigo did great work with his scrapers. Anyone who contribute to the open banking concept in Israel is a valued man. I chose a different strategy for the bank Leumi scraper since I prefer to use the 'wait' strategy against DOM anchors which doesn't care about network latency as opposed to 'pause for x seconds' strategy. I did like how he scraped the table and used the same approach with the puppeteer in the new scraper.

**Comment by esakal** [comment]
@eshaham can you create a new branch for this feature?
Thanks!

**Comment by eshaham** [comment]
@esakal done - called `add_memo_field`

**Comment by eshaham** [comment]
@esakal pushed code to add `memo` field to Leumi Card and Isracard.
I also uncommented your code in Leumi scraper.
Discount doesn't seem to have any relevant field.
In Visa Cal there seem to be 2 relevant fields, but I don't have transactions with data in these fields, so couldn't figure out what to do. Maybe @nirgin could help?

We're still missing Bank Hapoalim - @sebikaplun @jonathanrauch, need help 😄

**Comment by esakal** [comment]
@eshaham which scrapers are we missing to merge `add_memo_field` into master?

**Comment by eshaham** [comment]
@esakal just Hapoalim AFAIK

**Comment by esakal** [comment]
@eshaham is it possible to merge `add_memo_field` into `master`? i think it will be very useful with what we already have even without the missing support in the Hapoalim.

**Comment by eshaham** [comment]
@esakal I see you managed to get access to Hapoalim account 😄 
Create a PR #124, can you please check the conflict in Hapoalim scraper?

**Comment by esakal** [comment]
@eshaham I fixed the conflict in #125. I didn't know if you want the base to be `master` or `add_memo_field` but as I mentioned in the new PR feel free to edit and change the base branch

**Comment by eshaham** [comment]
This is now implemented in all scrapers 🎉
