### ISSUE TITLE
[Cal] Issue: cannot scrape Cal

### ISSUE THREAD

**Issue by gczobel** [eshaham/israeli-bank-scrapers#834]
Hi, anyone else is having issues with Cal?
My scrape fails trying to login:

GENERIC waiting for selector `button.btn-close` failed: timeout 30000ms exceeded

**Comment by gczobel** [comment]
@baruchiro @galbarm @daniel-hauser
I renamed the issue. A `GENERIC` error is return instead of `CHANGE_PASSWORD`. Only after I entered in the web page and tried to login the issue was found.

**Comment by daniel-hauser** [comment]
@gczobel The cal scraper has no change password detection - see [visa-cal.js:165](https://github.com/eshaham/israeli-bank-scrapers/blob/3d031d1bdc0858aaee7362c32e7d3eabbd463bf1/src/scrapers/visa-cal.ts#L165C22-L165C36)

Any chance you remember the exact message you got? This will allow us to add support for this scenario

**Comment by gczobel** [comment]
No... sorry... I copied that only part from the log, that is lost.

**Comment by baruchiro** [comment]
Visa-Cal is working for me. The `timeout 30000ms exceeded` sometimes happened because of a slow internet or something similar.

Did you try to run it while showing the browser? You may find unexpected behavior like an error message from the website, or a new popup for a new service...

**Comment by gczobel** [comment]
> Visa-Cal is working for me. The `timeout 30000ms exceeded` sometimes happened because of a slow internet or something similar.
> 
> 
> 
> Did you try to run it while showing the browser? You may find unexpected behavior like an error message from the website, or a new popup for a new service...
> 
> 
> 
> 

Not relevant. Check my message https://github.com/eshaham/israeli-bank-scrapers/issues/834#issuecomment-1937051304

**Comment by baruchiro** [comment]
I'm not sure I understand. Are you saying that the problem is that you get a GENERIC_ERROR instead of CHANGE_PASSWORD?

And after you changed your password, did the scraper work for you?

**Comment by eshaham** [comment]
Just ran into the same issue, added a PR to add change password support to visa cal: #845
