### ISSUE TITLE
FIBI - Beinleumi - Help needed for adding multiple account support

### ISSUE THREAD

**Issue by nissant** [eshaham/israeli-bank-scrapers#837]
I see multiple accounts are to-do, any chance to get this in any time soon? 
Can I help with this?
https://github.com/eshaham/israeli-bank-scrapers/blob/85d507a1e5bd61ab4e9a0267aa4eb86f60f8918d/src/scrapers/base-beinleumi-group.ts#L284

**Comment by baruchiro** [comment]
Hi, for each bank it depends on whether there is someone with an account on that bank to develop the scraper.

If you're a developer, we are welcome to contributors!

**Comment by nissant** [comment]
Got it. I am using FIBI with multiple accounts so this could help me a lot.
Will try to onboard and get something to work in a PR.
