### ISSUE TITLE
VISA CAL FAILURE

### ISSUE THREAD

**Issue by agammyshhay** [eshaham/israeli-bank-scrapers#841]
there is a repeated bug with VISA CAL :
" waiting for selector `button.btn-close` failed: timeout 30000ms exceeded"

thanks

**Comment by baruchiro** [comment]
VisaCal worked for me today 🤷‍♂️

**Comment by baruchiro** [comment]
@galbarm @daniel-hauser Please take a look

**Comment by daniel-hauser** [comment]
Cal is working for me as well.
![cal scrape status](https://github.com/eshaham/israeli-bank-scrapers/assets/36034483/f69f7e3a-cf18-4573-a307-48f159beb5aa)


@agammyshhay Is your password expired by any chance? If so, maybe the change password ui was changed and needs to be updated in the scraper

**Comment by baruchiro** [comment]
Closed.

Yes, we need to update the "CHANE_PASSWORD" catch, I hope that one of us will notice this next time we need to change the password 😉
