### ISSUE TITLE
Behatsdaa scrapper return wrong sign

### ISSUE THREAD

**Issue by liranelisha** [eshaham/israeli-bank-scrapers#851]
all expenses made with the Behatsdaa card are returned with positive sign (ex. "230") while every other scrapper is returning a negative sign for expenses (ex. "-230").

all scrappers should return the same sign

**Comment by baruchiro** [comment]
Do you plan to fix it? Sounds like a tiny change.

**Comment by liranelisha** [comment]
do you mind setting my permissions to "write" or higher in order for me to be able to open a PR?

**Comment by liranelisha** [comment]
i had to create a fork from the master as i do not have write permissions.
https://github.com/eshaham/israeli-bank-scrapers/pull/852 open, but i don't know if the workflows are on hold due to the fork or something else

**Comment by baruchiro** [comment]
Yes, although forks are annoying, they are our way to contribute to open source.

You can see [how many forks I have](https://github.com/baruchiro?tab=repositories&q=&type=fork&language=&sort=) just because I wanted to patch something.

**Comment by liranelisha** [comment]
it seems i had an older version where the sign was wrong
