### ISSUE TITLE
Dependencies versions & security vulnerabilities

### ISSUE THREAD

**Issue by yanivfranco** [eshaham/israeli-bank-scrapers#855]
First, I want say thanks to all the contributors of this project! it is awesome and useful.

The only problem is that most of the dependencies of this repository are SUPER outdated, resulting in lots of security vulnerabilities. This is a big issue when this project is used to  access some very sensitive information.
Are there any plans on updating the dependencies ?

I noticed this general issue because of a bug with outdated puppeteer..
This is a known issue which is fixed in puppeteer v12 https://github.com/puppeteer/puppeteer/issues/7455
I noticed puppeteer version is 6.0.0, which was release on 2021... and is quite outdated. 
Is there any reason why the version is not updated? 
I could maybe try and contribute it myself if there are no objections...

Thanks

**Comment by baruchiro** [comment]
I have no objections, please try.

**Comment by yanivfranco** [comment]
@baruchiro I have a PR ready to be pushed, just need the right permissions.... 🙏

**Comment by baruchiro** [comment]
Hi, if it is your first time contributing on Github, you need to fork this repository and open a pull request from your fork to ours.

Read more here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

If you need any help please ask me.

**Comment by yanivfranco** [comment]
@baruchiro https://github.com/eshaham/israeli-bank-scrapers/pull/862

**Comment by baruchiro** [comment]
Done by https://github.com/eshaham/israeli-bank-scrapers/pull/862
