### ISSUE TITLE
Bank Otsar HaHayal is failing to fetch data

### ISSUE THREAD

**Issue by ReaBar** [eshaham/israeli-bank-scrapers#858]
After a successful login, a function tries to verify that the URL is as expected. However, the bank added a new ID to the URL, so this function failed.

The new string ID:
![Otsar](https://github.com/eshaham/israeli-bank-scrapers/assets/7058865/389f4047-52e8-4d65-8318-eb3bd472e677)

The function that fails:
`getKeyByValue`
....
`  } else {
      result = value.toLowerCase() === condition.toLowerCase();
   }`

**Comment by ReaBar** [comment]
I saw there is an open PR that needs to be fixed and merged to solve this issue
[PR](https://github.com/eshaham/israeli-bank-scrapers/pull/856)
@baruchiro can you handle it?

**Comment by baruchiro** [comment]
You're right.

Can you test the change with the local Jest tests?

**Comment by ReaBar** [comment]
@baruchiro I'm unfamiliar with jest tests, but I did a local test with the change @matanelgabsi did, and it worked.
If you can briefly explain how I run the test suite, I will be glad to be added as a tester to Otsar HaHayal.
