### ISSUE TITLE
failing to scrape mizrachi 

### ISSUE THREAD

**Issue by ohadperry** [eshaham/israeli-bank-scrapers#877]
using A docker image to run this project 
https://github.com/daniel-hauser/moneyman
the docker does not open a chromium tab (on purpose)

```
import { createScraper, ScraperScrapingResult } from "israeli-bank-scrapers";
const scraper = createScraper({
      startDate,
      companyId: account.companyId,
      verbose: true,
      args: ["--disable-dev-shm-usage", "--no-sandbox"],
      futureMonthsToScrape: Number.isNaN(futureMonthsToScrape)
        ? undefined
        : futureMonthsToScrape,
    });
```
the scraper works for leumi but not for mizrachi
my laptop running the docker is Apple M2
here is the docker output for leumi and mizrach. leumi is successfull but mizrachi fails which means the issue is most likely with the specific mizrach scraper (or it's options)
Error: failed to find element matching selector "a[href*="/osh/legacy/legacy-Osh-p420"]"

<img width="1117" alt="aaaaa" src="https://github.com/user-attachments/assets/1b49d77b-3b0a-4212-a23c-f8e3a5b50969">

**Comment by baruchiro** [comment]
Maybe there is an error with [moneyman](https://github.com/daniel-hauser/moneyman)? Mizrahi scraper worked for me this morning.

Usually, the way to check this is to launch the project with a browser view to check what failed.
If you can't do it with [moneyman](https://github.com/daniel-hauser/moneyman), please run the tests of this project to check what goes wrong.

**Comment by ohadperry** [comment]
on my localhost the browser opens and is stuck
about running tests, do you have a github actions file that I can use to run tests?
I looked for it in this project here https://github.com/eshaham/israeli-bank-scrapers/tree/master/.github/workflows
and couldn't find anything relevant

**Comment by baruchiro** [comment]
To run tests you need to clone the [`.tests-config.tpl.js`](https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/tests/.tests-config.tpl.js) to `.tests-config.js`, fill it and run `npm test`.

**Comment by ohadperry** [comment]
I did do that. the issue is not running the tests, is creating an environment to run the tests with passing. 
I've created a github [codespace](https://miniature-halibut-96g4j75qxrcpp6p.github.dev/) to get this work. 
that's why I'm asking for the github actions yml if you have it. 


```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

I've installed chromium browser on the machine
```
sudo apt-get install chromium-browser
```
getting this error 
<img width="1385" alt="image" src="https://github.com/user-attachments/assets/ded81f6d-c802-4408-8527-9dffb7bfc581">

tried solving it with these args:
```
options: { // options object that is passed to the scrapers. see more in readme.md file
    startDate,
    combineInstallments: false,
    showBrowser: false,
    verbose: transpileModule,
    args: ["--disable-dev-shm-usage", "--no-sandbox", " --headless", "--disable-gpu"],
    storeFailureScreenShotPath: false // path.resolve(__dirname, 'snapshots/failure.jpg')
  },

and 
sudo apt-get install xvfb
```

still getting the error. 
seems that codespace instance is not the best solution to run this.
