### ISSUE TITLE
Leumi bank scraper times out

### ISSUE THREAD

**Issue by ifeins** [eshaham/israeli-bank-scrapers#94]
I'm using the latest version of `israeli-ynab-updater` which uses `israeli-bank-scrapers` version `0.5.5`.

When I'm trying to scrape Leumi I get the following output:

```
Bank Leumi: START_SCRAPING
Bank Leumi: INITIALIZING
Bank Leumi: LOGGING_IN
Bank Leumi: TERMINATING
Bank Leumi: END_SCRAPING
success: false
error type: generic
error: waiting failed: timeout 30000ms exceeded
```

**Comment by ifeins** [comment]
cc: @esakal

**Comment by ifeins** [comment]
I tried logging in from web and then after login I got a message that my password is about to expire and I need to change it - this is why the scraper failed.

So there isn't any issue, although it would be nice to have the scraper identify this scenario and write a message to the console about the need to change the password :)

**Comment by esakal** [comment]
Hi @ifeins,
You are absolutely right, the scraper should identify such a scenario, I even added a placeholder as a reminder about it [here](https://github.com/eshaham/israeli-bank-scrapers/blob/master/src/scrapers/leumi.js#L150) hoping to complete it once my password will expire. I'm probably too late and you already changed your password so you cannot extract the selectors needed to identify such a scenario. 

If anyone else encounter this scenario and reviewing the issues for a solution, please save the page source, remove the credentials if found on that page and attach it so i will be able to update the scraper accordingly.

Thanks
Eran.
